In [2]:
# Import libraries

import pandas as pd
import numpy as np

from pathlib import Path

In [3]:
# Project root directory

PROJECT_ROOT = Path.cwd().resolve()

print("Current working directory:")
print(PROJECT_ROOT)

Current working directory:
C:\Users\Aditya\Smart_traffic_management\notebooks

In [4]:
# Project root directory

PROJECT_ROOT = Path.cwd().parent

print("Project root:")
print(PROJECT_ROOT)

print("\nProject root exists:", PROJECT_ROOT.exists())

Project root:
c:\Users\Aditya\Smart_traffic_management

Project root exists: True

In [5]:
# Project directories

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

print("Data directory:")
print(DATA_DIR)

print("\nRaw data directory:")
print(RAW_DATA_DIR)

print("\nProcessed data directory:")
print(PROCESSED_DATA_DIR)

Data directory:
c:\Users\Aditya\Smart_traffic_management\data

Raw data directory:
c:\Users\Aditya\Smart_traffic_management\data\raw

Processed data directory:
c:\Users\Aditya\Smart_traffic_management\data\processed

In [6]:
# Inspect processed data files

if PROCESSED_DATA_DIR.exists():
    processed_files = list(PROCESSED_DATA_DIR.iterdir())

    print("Files in processed directory:")
    
    for file in processed_files:
        print(f"- {file.name}")
else:
    print("Processed data directory does not exist.")

Files in processed directory:
- featured
- traffic_2025.csv

In [7]:
# Check sizes of processed data files

for file in PROCESSED_DATA_DIR.iterdir():
    if file.is_file():
        size_mb = file.stat().st_size / (1024 ** 2)

        print(
            f"{file.name:<40} "
            f"{size_mb:,.2f} MB"
        )

traffic_2025.csv                         9,982.55 MB

In [8]:
# Inspect the processed dataset structure

DATA_FILE = PROCESSED_DATA_DIR / "traffic_2025.csv"

sample_data = pd.read_csv(
    DATA_FILE,
    nrows=5
)

print("Columns:")
print(sample_data.columns.tolist())

print("\nShape of sample:")
print(sample_data.shape)

display(sample_data.head())

Columns:
['NB_SCATS_SITE', 'QT_INTERVAL_COUNT', 'NB_DETECTOR', 'V00', 'V01', 'V02', 'V03', 'V04', 'V05', 'V06', 'V07', 'V08', 'V09', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95', 'NM_REGION', 'CT_RECORDS', 'QT_VOLUME_24HOUR', 'CT_ALARM_24HOUR']

Shape of sample:
(5, 103)

,NB_SCATS_SITE,QT_INTERVAL_COUNT,NB_DETECTOR,V00,V01,V02,V03,V04,V05,V06,...,V90,V91,V92,V93,V94,V95,NM_REGION,CT_RECORDS,QT_VOLUME_24HOUR,CT_ALARM_24HOUR
0,100,2025-04-01,1,2,1,1,2,4,1,4,...,12,9,4,7,3,3,WV1,96,992,0
1,100,2025-04-01,2,12,18,4,9,5,5,7,...,28,32,29,22,13,8,WV1,96,8881,0
2,100,2025-04-01,3,22,8,8,10,8,10,8,...,58,55,48,29,21,28,WV1,96,8905,0
3,100,2025-04-01,4,17,9,9,6,5,6,3,...,38,34,22,18,13,17,WV1,96,8547,0
4,100,2025-04-01,5,3,3,2,1,2,4,0,...,5,3,14,3,3,2,WV1,96,994,0

In [9]:
# Inspect data types

print("Data types:")

display(
    sample_data.dtypes.to_frame(
        name="dtype"
    )
)

Data types:

                   dtype
NB_SCATS_SITE      int64
QT_INTERVAL_COUNT    str
NB_DETECTOR        int64
V00                int64
V01                int64
...                  ...
V95                int64
NM_REGION            str
CT_RECORDS         int64
QT_VOLUME_24HOUR   int64
CT_ALARM_24HOUR    int64

[103 rows x 1 columns]

In [10]:
# Identify traffic volume columns

traffic_columns = [
    column
    for column in sample_data.columns
    if column.startswith("V")
    and column[1:].isdigit()
]

print("Number of traffic interval columns:", len(traffic_columns))

print("\nFirst five:")
print(traffic_columns[:5])

print("\nLast five:")
print(traffic_columns[-5:])

Number of traffic interval columns: 96

First five:
['V00', 'V01', 'V02', 'V03', 'V04']

Last five:
['V91', 'V92', 'V93', 'V94', 'V95']

In [11]:
# Compact data-type summary

dtype_summary = pd.DataFrame({
    "column": sample_data.columns,
    "dtype": sample_data.dtypes.astype(str).values
})

display(dtype_summary)

                column  dtype
0        NB_SCATS_SITE  int64
1    QT_INTERVAL_COUNT    str
2          NB_DETECTOR  int64
3                  V00  int64
4                  V01  int64
..                 ...    ...
98                 V95  int64
99           NM_REGION    str
100         CT_RECORDS  int64
101   QT_VOLUME_24HOUR  int64
102    CT_ALARM_24HOUR  int64

[103 rows x 2 columns]

In [12]:
# Check missing values in the sample

missing_summary = (
    sample_data
    .isna()
    .sum()
    .to_frame(name="missing_count")
)

missing_summary["missing_percentage"] = (
    missing_summary["missing_count"]
    / len(sample_data)
    * 100
)

display(
    missing_summary[
        missing_summary["missing_count"] > 0
    ]
)

Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

In [13]:
# Inspect the date column

print(
    "QT_INTERVAL_COUNT dtype:",
    sample_data["QT_INTERVAL_COUNT"].dtype
)

print("\nSample date values:")

display(
    sample_data["QT_INTERVAL_COUNT"]
)

QT_INTERVAL_COUNT dtype: str

Sample date values:

0    2025-04-01
1    2025-04-01
2    2025-04-01
3    2025-04-01
4    2025-04-01
Name: QT_INTERVAL_COUNT, dtype: str

In [14]:
# Define columns needed for feature engineering

id_columns = [
    "NB_SCATS_SITE",
    "QT_INTERVAL_COUNT",
    "NB_DETECTOR",
    "NM_REGION"
]

feature_input_columns = (
    id_columns
    + traffic_columns
)

print(
    "Number of columns required:",
    len(feature_input_columns)
)

print("\nColumns:")
print(feature_input_columns)

Number of columns required: 100

Columns:
['NB_SCATS_SITE', 'QT_INTERVAL_COUNT', 'NB_DETECTOR', 'NM_REGION', 'V00', 'V01', 'V02', 'V03', 'V04', 'V05', 'V06', 'V07', 'V08', 'V09', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95']

In [15]:
# Verify required columns exist in the dataset

missing_required_columns = [
    column
    for column in feature_input_columns
    if column not in sample_data.columns
]

if missing_required_columns:
    print("Missing columns:")
    print(missing_required_columns)
else:
    print("All required columns are present.")

All required columns are present.

In [16]:
# Convert the date column to datetime in the sample

sample_data["QT_INTERVAL_COUNT"] = pd.to_datetime(
    sample_data["QT_INTERVAL_COUNT"]
)

print(
    "QT_INTERVAL_COUNT dtype:",
    sample_data["QT_INTERVAL_COUNT"].dtype
)

display(
    sample_data[
        [
            "NB_SCATS_SITE",
            "QT_INTERVAL_COUNT",
            "NB_DETECTOR"
        ]
    ]
)

QT_INTERVAL_COUNT dtype: datetime64[us]

   NB_SCATS_SITE QT_INTERVAL_COUNT  NB_DETECTOR
0            100        2025-04-01            1
1            100        2025-04-01            2
2            100        2025-04-01            3
3            100        2025-04-01            4
4            100        2025-04-01            5

In [17]:
# Test chunked reading

CHUNK_SIZE = 50_000

chunk = pd.read_csv(
    DATA_FILE,
    usecols=feature_input_columns,
    nrows=CHUNK_SIZE
)

print("Chunk shape:")
print(chunk.shape)

print("\nChunk memory usage:")
memory_mb = (
    chunk.memory_usage(deep=True).sum()
    / (1024 ** 2)
)

print(f"{memory_mb:.2f} MB")

Chunk shape:
(50000, 100)

Chunk memory usage:
38.77 MB

In [18]:
# Inspect the chunk

display(
    chunk[
        [
            "NB_SCATS_SITE",
            "QT_INTERVAL_COUNT",
            "NB_DETECTOR",
            "NM_REGION",
            "V00",
            "V01",
            "V02",
            "V95"
        ]
    ].head(10)
)

   NB_SCATS_SITE QT_INTERVAL_COUNT  NB_DETECTOR NM_REGION  V00  V01  V02  V95
0            100        2025-04-01            1       WV1    2    1    1    3
1            100        2025-04-01            2       WV1   12   18    4    8
2            100        2025-04-01            3       WV1   22    8    8   28
3            100        2025-04-01            4       WV1   17    9    9   17
4            100        2025-04-01            5       WV1    3    3    2    2
5            100        2025-04-01            6       WV1    0    0    0    0
6            100        2025-04-01            7       WV1    0    0    0    0
7            100        2025-04-01            8       WV1    0    0    0    0
8            100        2025-04-01            9       WV1    0    0    0    0
9            100        2025-04-01           10       WV1    0    0    0    0

In [19]:
# Check chunk data types

display(
    chunk.dtypes.to_frame(
        name="dtype"
    )
)

                   dtype
NB_SCATS_SITE      int64
QT_INTERVAL_COUNT    str
NB_DETECTOR        int64
V00                int64
V01                int64
...                  ...
V92                int64
V93                int64
V94                int64
V95                int64
NM_REGION            str

[100 rows x 1 columns]

In [20]:
# Convert the date column in the chunk

chunk["QT_INTERVAL_COUNT"] = pd.to_datetime(
    chunk["QT_INTERVAL_COUNT"]
)

print(
    "QT_INTERVAL_COUNT dtype:",
    chunk["QT_INTERVAL_COUNT"].dtype
)

display(
    chunk[
        [
            "QT_INTERVAL_COUNT",
            "NB_SCATS_SITE",
            "NB_DETECTOR"
        ]
    ].head()
)

QT_INTERVAL_COUNT dtype: datetime64[us]

  QT_INTERVAL_COUNT  NB_SCATS_SITE  NB_DETECTOR
0        2025-04-01            100            1
1        2025-04-01            100            2
2        2025-04-01            100            3
3        2025-04-01            100            4
4        2025-04-01            100            5

In [21]:
# Inspect the ordering of the raw dataset

order_check = chunk[
    [
        "NB_SCATS_SITE",
        "NB_DETECTOR",
        "QT_INTERVAL_COUNT"
    ]
].copy()

display(order_check.head(20))

print("\nFirst 10 site IDs:")
print(order_check["NB_SCATS_SITE"].head(10).tolist())

print("\nFirst 10 detector IDs:")
print(order_check["NB_DETECTOR"].head(10).tolist())

print("\nUnique dates in this chunk:")
print(order_check["QT_INTERVAL_COUNT"].nunique())

    NB_SCATS_SITE  NB_DETECTOR QT_INTERVAL_COUNT
0             100            1        2025-04-01
1             100            2        2025-04-01
2             100            3        2025-04-01
3             100            4        2025-04-01
4             100            5        2025-04-01
5             100            6        2025-04-01
6             100            7        2025-04-01
7             100            8        2025-04-01
8             100            9        2025-04-01
9             100           10        2025-04-01
10            100           11        2025-04-01
11            100           12        2025-04-01
12            100           13        2025-04-01
13            100           14        2025-04-01
14            100           15        2025-04-01
15            100           16        2025-04-01
16            100           17        2025-04-01
17            100           18        2025-04-01
18            100           19        2025-04-01
19            100           20        2025-04-01

First 10 site IDs:
[100, 100, 100, 100, 100, 100, 100, 100, 100, 100]

First 10 detector IDs:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Unique dates in this chunk:
1

In [22]:
# Inspect the distribution of rows across dates in the chunk

date_counts = (
    chunk["QT_INTERVAL_COUNT"]
    .value_counts()
    .sort_index()
)

display(date_counts)

QT_INTERVAL_COUNT
2025-04-01    50000
Name: count, dtype: int64

In [23]:
# Check how site-detector combinations are ordered

site_detector = (
    chunk[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR"
        ]
    ]
    .drop_duplicates()
)

print(
    "Unique site-detector combinations:",
    len(site_detector)
)

display(
    site_detector.head(30)
)

Unique site-detector combinations: 50000

    NB_SCATS_SITE  NB_DETECTOR
0             100            1
1             100            2
2             100            3
3             100            4
4             100            5
5             100            6
6             100            7
7             100            8
8             100            9
9             100           10
10            100           11
11            100           12
12            100           13
13            100           14
14            100           15
15            100           16
16            100           17
17            100           18
18            100           19
19            100           20
20            100           21
21            100           22
22            100           23
23            100           24
24            101            1
25            101            2
26            101            3
27            101            4
28            101            5
29            101            6

In [24]:
# Inspect consecutive chunks to understand file ordering

reader = pd.read_csv(
    DATA_FILE,
    usecols=feature_input_columns,
    chunksize=CHUNK_SIZE
)

chunk_1 = next(reader)
chunk_2 = next(reader)

chunk_1["QT_INTERVAL_COUNT"] = pd.to_datetime(
    chunk_1["QT_INTERVAL_COUNT"]
)

chunk_2["QT_INTERVAL_COUNT"] = pd.to_datetime(
    chunk_2["QT_INTERVAL_COUNT"]
)

print("Chunk 1:")
print("Rows:", len(chunk_1))
print("First date:", chunk_1["QT_INTERVAL_COUNT"].min())
print("Last date:", chunk_1["QT_INTERVAL_COUNT"].max())

print("\nChunk 2:")
print("Rows:", len(chunk_2))
print("First date:", chunk_2["QT_INTERVAL_COUNT"].min())
print("Last date:", chunk_2["QT_INTERVAL_COUNT"].max())

Chunk 1:
Rows: 50000
First date: 2025-04-01 00:00:00
Last date: 2025-04-01 00:00:00

Chunk 2:
Rows: 50000
First date: 2025-04-01 00:00:00
Last date: 2025-04-01 00:00:00

In [25]:
# Inspect the boundary between consecutive chunks

print("Last rows of Chunk 1:")

display(
    chunk_1[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "QT_INTERVAL_COUNT"
        ]
    ].tail(10)
)

print("\nFirst rows of Chunk 2:")

display(
    chunk_2[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "QT_INTERVAL_COUNT"
        ]
    ].head(10)
)

Last rows of Chunk 1:

       NB_SCATS_SITE  NB_DETECTOR QT_INTERVAL_COUNT
49990           2908           20        2025-04-01
49991           2908           21        2025-04-01
49992           2908           22        2025-04-01
49993           2908           23        2025-04-01
49994           2908           24        2025-04-01
49995           2909            1        2025-04-01
49996           2909            2        2025-04-01
49997           2909            3        2025-04-01
49998           2909            4        2025-04-01
49999           2909            5        2025-04-01

First rows of Chunk 2:

       NB_SCATS_SITE  NB_DETECTOR QT_INTERVAL_COUNT
50000           2909            6        2025-04-01
50001           2909            7        2025-04-01
50002           2909            8        2025-04-01
50003           2909            9        2025-04-01
50004           2909           10        2025-04-01
50005           2909           11        2025-04-01
50006           2909           12        2025-04-01
50007           2909           13        2025-04-01
50008           2909           14        2025-04-01
50009           2909           15        2025-04-01

In [26]:
# Compare date distributions across the two chunks

print("Chunk 1 date distribution:")

display(
    chunk_1["QT_INTERVAL_COUNT"]
    .value_counts()
    .sort_index()
)

print("\nChunk 2 date distribution:")

display(
    chunk_2["QT_INTERVAL_COUNT"]
    .value_counts()
    .sort_index()
)

Chunk 1 date distribution:

QT_INTERVAL_COUNT
2025-04-01    50000
Name: count, dtype: int64

Chunk 2 date distribution:

QT_INTERVAL_COUNT
2025-04-01    50000
Name: count, dtype: int64

In [27]:
# Inspect the exact boundary between two chunks

print("Last 5 rows of Chunk 1:")
print(
    chunk_1[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "QT_INTERVAL_COUNT"
        ]
    ]
    .tail(5)
    .to_string(index=False)
)

print("\nFirst 5 rows of Chunk 2:")
print(
    chunk_2[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "QT_INTERVAL_COUNT"
        ]
    ]
    .head(5)
    .to_string(index=False)
)

Last 5 rows of Chunk 1:
 NB_SCATS_SITE  NB_DETECTOR QT_INTERVAL_COUNT
          2909            1        2025-04-01
          2909            2        2025-04-01
          2909            3        2025-04-01
          2909            4        2025-04-01
          2909            5        2025-04-01

First 5 rows of Chunk 2:
 NB_SCATS_SITE  NB_DETECTOR QT_INTERVAL_COUNT
          2909            6        2025-04-01
          2909            7        2025-04-01
          2909            8        2025-04-01
          2909            9        2025-04-01
          2909           10        2025-04-01

In [28]:
# Check whether site IDs are non-decreasing within the chunks

chunk_1_site_sorted = (
    chunk_1["NB_SCATS_SITE"]
    .is_monotonic_increasing
)

chunk_2_site_sorted = (
    chunk_2["NB_SCATS_SITE"]
    .is_monotonic_increasing
)

print("Chunk 1 site IDs sorted:", chunk_1_site_sorted)
print("Chunk 2 site IDs sorted:", chunk_2_site_sorted)

Chunk 1 site IDs sorted: True
Chunk 2 site IDs sorted: True

In [29]:
# Check detector ordering within each site

detector_order_check = (
    chunk_1
    .groupby("NB_SCATS_SITE")["NB_DETECTOR"]
    .apply(lambda x: x.is_monotonic_increasing)
)

print(
    "Sites with non-increasing detector order:",
    (~detector_order_check).sum()
)

Sites with non-increasing detector order: 0

In [30]:
# Inspect the number of rows per site in the first chunk

site_row_counts = (
    chunk_1["NB_SCATS_SITE"]
    .value_counts()
    .sort_index()
)

display(
    site_row_counts.head(20)
)

print(
    "\nNumber of unique sites:",
    site_row_counts.size
)

NB_SCATS_SITE
100    24
101    24
102    24
103    24
104    24
105    24
106    24
107    32
108    24
109    24
111    24
112    24
113    24
114    32
115    24
116    24
117    24
118    24
119    24
120    24
Name: count, dtype: int64

Number of unique sites: 2024

## Raw File Ordering

Inspection of consecutive chunks shows that the processed CSV is ordered by:

1. Date (`QT_INTERVAL_COUNT`)
2. SCATS site (`NB_SCATS_SITE`)
3. Detector (`NB_DETECTOR`)

Site IDs are non-decreasing within the tested chunks, and detector IDs are ordered within sites.

Because chunk boundaries can occur inside a site, feature engineering should not calculate temporal lags independently within each raw CSV chunk.

The processing strategy will therefore preserve temporal history across chunks and process complete dates before generating the final time-series features.

In [31]:
# Temporal feature configuration

LAG_PERIODS = [
    1,      # 15 minutes
    2,      # 30 minutes
    3,      # 45 minutes
    4,      # 60 minutes
    96      # previous day, same 15-minute interval
]

ROLLING_WINDOWS = [
    4,      # previous 1 hour
    8       # previous 2 hours
]

print("Lag periods:", LAG_PERIODS)
print("Rolling windows:", ROLLING_WINDOWS)

Lag periods: [1, 2, 3, 4, 96]
Rolling windows: [4, 8]

In [32]:
# Define the final temporal feature names

TEMPORAL_FEATURES = [
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_4",
    "lag_96",
    "rolling_mean_4",
    "rolling_std_4",
    "rolling_mean_8",
    "hour",
    "minute",
    "day_of_week",
    "is_weekend",
    "time_index"
]

TARGET_COLUMN = "target"

print("Temporal features:")
for feature in TEMPORAL_FEATURES:
    print("-", feature)

print("\nTarget:", TARGET_COLUMN)

Temporal features:
- lag_1
- lag_2
- lag_3
- lag_4
- lag_96
- rolling_mean_4
- rolling_std_4
- rolling_mean_8
- hour
- minute
- day_of_week
- is_weekend
- time_index

Target: target

In [33]:
# Convert one day's wide-format traffic data into long format

def reshape_daily_traffic(day_data):
    """
    Convert V00-V95 traffic columns into timestamped long-format data.
    """

    traffic_long = day_data.melt(
        id_vars=[
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "QT_INTERVAL_COUNT",
            "NM_REGION"
        ],
        value_vars=traffic_columns,
        var_name="interval",
        value_name="volume"
    )

    # Extract interval number from V00, V01, ..., V95
    traffic_long["interval"] = (
        traffic_long["interval"]
        .str.replace("V", "", regex=False)
        .astype("int8")
    )

    # Create the 15-minute time offset
    traffic_long["time"] = pd.to_timedelta(
        traffic_long["interval"] * 15,
        unit="m"
    )

    # Create the actual timestamp
    traffic_long["timestamp"] = (
        traffic_long["QT_INTERVAL_COUNT"]
        + traffic_long["time"]
    )

    return traffic_long

In [34]:
# Test the daily reshape function

test_date = chunk_1["QT_INTERVAL_COUNT"].iloc[0]

test_day = chunk_1[
    chunk_1["QT_INTERVAL_COUNT"] == test_date
].copy()

test_long = reshape_daily_traffic(test_day)

print("Original daily shape:")
print(test_day.shape)

print("\nLong-format shape:")
print(test_long.shape)

display(
    test_long[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "QT_INTERVAL_COUNT",
            "interval",
            "timestamp",
            "volume"
        ]
    ].head(20)
)

Original daily shape:
(50000, 100)

Long-format shape:
(4800000, 8)

    NB_SCATS_SITE  NB_DETECTOR QT_INTERVAL_COUNT  interval  timestamp  volume
0             100            1        2025-04-01         0 2025-04-01       2
1             100            2        2025-04-01         0 2025-04-01      12
2             100            3        2025-04-01         0 2025-04-01      22
3             100            4        2025-04-01         0 2025-04-01      17
4             100            5        2025-04-01         0 2025-04-01       3
5             100            6        2025-04-01         0 2025-04-01       0
6             100            7        2025-04-01         0 2025-04-01       0
7             100            8        2025-04-01         0 2025-04-01       0
8             100            9        2025-04-01         0 2025-04-01       0
9             100           10        2025-04-01         0 2025-04-01       0
10            100           11        2025-04-01         0 2025-04-01       0
11            100           12        2025-04-01         0 2025-04-01       0
12            100           13        2025-04-01         0 2025-04-01       0
13            100           14        2025-04-01         0 2025-04-01       2
14            100           15        2025-04-01         0 2025-04-01       0
15            100           16        2025-04-01         0 2025-04-01       1
16            100           17        2025-04-01         0 2025-04-01       0
17            100           18        2025-04-01         0 2025-04-01       0
18            100           19        2025-04-01         0 2025-04-01       0
19            100           20        2025-04-01         0 2025-04-01       0

In [35]:
# Validate the daily reshape

rows_per_day_record = (
    test_long
    .groupby(
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "QT_INTERVAL_COUNT"
        ]
    )
    .size()
)

print(
    "Expected intervals per site-detector-date: 96"
)

print(
    "\nInterval count distribution:"
)

display(
    rows_per_day_record
    .value_counts()
    .sort_index()
)

Expected intervals per site-detector-date: 96

Interval count distribution:

96    50000
Name: count, dtype: int64

In [36]:
# Validate timestamp boundaries

print("Minimum timestamp:")
print(test_long["timestamp"].min())

print("\nMaximum timestamp:")
print(test_long["timestamp"].max())

print("\nUnique timestamps:")
print(test_long["timestamp"].nunique())

Minimum timestamp:
2025-03-31 21:54:00

Maximum timestamp:
2025-04-01 02:00:00

Unique timestamps:
96

In [37]:
# Inspect the original interval/date values

print("QT_INTERVAL_COUNT values:")

display(
    test_day[
        [
            "QT_INTERVAL_COUNT"
        ]
    ].drop_duplicates().head(20)
)

print(
    "\nData type:",
    test_day["QT_INTERVAL_COUNT"].dtype
)

QT_INTERVAL_COUNT values:

  QT_INTERVAL_COUNT
0        2025-04-01

Data type: datetime64[us]

In [38]:
# Inspect how the timestamp was constructed

display(
    test_long[
        [
            "QT_INTERVAL_COUNT",
            "interval",
            "time",
            "timestamp"
        ]
    ].head(20)
)

   QT_INTERVAL_COUNT  interval   time  timestamp
0         2025-04-01         0 0 days 2025-04-01
1         2025-04-01         0 0 days 2025-04-01
2         2025-04-01         0 0 days 2025-04-01
3         2025-04-01         0 0 days 2025-04-01
4         2025-04-01         0 0 days 2025-04-01
5         2025-04-01         0 0 days 2025-04-01
6         2025-04-01         0 0 days 2025-04-01
7         2025-04-01         0 0 days 2025-04-01
8         2025-04-01         0 0 days 2025-04-01
9         2025-04-01         0 0 days 2025-04-01
10        2025-04-01         0 0 days 2025-04-01
11        2025-04-01         0 0 days 2025-04-01
12        2025-04-01         0 0 days 2025-04-01
13        2025-04-01         0 0 days 2025-04-01
14        2025-04-01         0 0 days 2025-04-01
15        2025-04-01         0 0 days 2025-04-01
16        2025-04-01         0 0 days 2025-04-01
17        2025-04-01         0 0 days 2025-04-01
18        2025-04-01         0 0 days 2025-04-01
19        2025-04-01         0 0 days 2025-04-01

In [39]:
# Read a few raw values of QT_INTERVAL_COUNT

raw_check = pd.read_csv(
    DATA_FILE,
    usecols=["QT_INTERVAL_COUNT"],
    nrows=20
)

print(
    raw_check["QT_INTERVAL_COUNT"]
    .tolist()
)

['2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01', '2025-04-01']

In [40]:
# Convert one day's wide-format traffic data into long format

def reshape_daily_traffic(day_data):
    """
    Convert V00-V95 traffic columns into timestamped long-format data.
    """

    traffic_long = day_data.melt(
        id_vars=[
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "QT_INTERVAL_COUNT",
            "NM_REGION"
        ],
        value_vars=traffic_columns,
        var_name="interval",
        value_name="volume"
    )

    # Extract interval number from V00, V01, ..., V95
    # int16 is used to avoid overflow during minute calculation.
    traffic_long["interval"] = (
        traffic_long["interval"]
        .str.replace("V", "", regex=False)
        .astype("int16")
    )

    # Convert interval number into minutes after midnight
    traffic_long["minutes_after_midnight"] = (
        traffic_long["interval"] * 15
    )

    # Create the 15-minute time offset
    traffic_long["time"] = pd.to_timedelta(
        traffic_long["minutes_after_midnight"],
        unit="m"
    )

    # Create the actual timestamp
    traffic_long["timestamp"] = (
        traffic_long["QT_INTERVAL_COUNT"]
        + traffic_long["time"]
    )

    return traffic_long

In [41]:
# Recreate the test long-format data after fixing the interval dtype

test_long = reshape_daily_traffic(test_day)

print("Long-format shape:")
print(test_long.shape)

Long-format shape:
(4800000, 9)

In [42]:
# Validate interval and minute calculations

print(
    "Minimum interval:",
    test_long["interval"].min()
)

print(
    "Maximum interval:",
    test_long["interval"].max()
)

print(
    "Minimum minutes:",
    test_long["minutes_after_midnight"].min()
)

print(
    "Maximum minutes:",
    test_long["minutes_after_midnight"].max()
)

Minimum interval: 0
Maximum interval: 95
Minimum minutes: 0
Maximum minutes: 1425

In [43]:
# Check first and last 15-minute intervals

timestamp_check = (
    test_long[
        [
            "interval",
            "minutes_after_midnight",
            "timestamp"
        ]
    ]
    .drop_duplicates()
    .sort_values("interval")
)

display(
    pd.concat(
        [
            timestamp_check.head(5),
            timestamp_check.tail(5)
        ]
    )
)

         interval  minutes_after_midnight           timestamp
0               0                       0 2025-04-01 00:00:00
50000           1                      15 2025-04-01 00:15:00
100000          2                      30 2025-04-01 00:30:00
150000          3                      45 2025-04-01 00:45:00
200000          4                      60 2025-04-01 01:00:00
4550000        91                    1365 2025-04-01 22:45:00
4600000        92                    1380 2025-04-01 23:00:00
4650000        93                    1395 2025-04-01 23:15:00
4700000        94                    1410 2025-04-01 23:30:00
4750000        95                    1425 2025-04-01 23:45:00

In [44]:
# Explicitly validate the first and last timestamps

first_timestamp = (
    test_long.loc[
        test_long["interval"] == 0,
        "timestamp"
    ]
    .iloc[0]
)

last_timestamp = (
    test_long.loc[
        test_long["interval"] == 95,
        "timestamp"
    ]
    .iloc[0]
)

unique_timestamps = test_long["timestamp"].nunique()

print("First timestamp:", first_timestamp)
print("Last timestamp:", last_timestamp)
print("Unique timestamps:", unique_timestamps)

print("\nTimestamp validation:")

print(
    "First timestamp correct:",
    first_timestamp.time() == pd.Timestamp("00:00").time()
)

print(
    "Last timestamp correct:",
    last_timestamp.time() == pd.Timestamp("23:45").time()
)

print(
    "96 unique timestamps:",
    unique_timestamps == 96
)

First timestamp: 2025-04-01 00:00:00
Last timestamp: 2025-04-01 23:45:00
Unique timestamps: 96

Timestamp validation:
First timestamp correct: True
Last timestamp correct: True
96 unique timestamps: True

In [45]:
# Validate that timestamps are exactly 15 minutes apart

timestamp_intervals = (
    test_long[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp"
        ]
    ]
    .sort_values(
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp"
        ]
    )
    .groupby(
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR"
        ]
    )["timestamp"]
    .diff()
)

unexpected_intervals = (
    timestamp_intervals.dropna()
    != pd.Timedelta(minutes=15)
)

print(
    "Unexpected timestamp intervals:",
    unexpected_intervals.sum()
)

Unexpected timestamp intervals: 0

In [46]:
# Create calendar and time-of-day features

def add_time_features(data):
    """
    Add calendar and time-of-day features to timestamped traffic data.
    """

    data = data.copy()

    data["hour"] = data["timestamp"].dt.hour

    data["minute"] = data["timestamp"].dt.minute

    data["day_of_week"] = data["timestamp"].dt.dayofweek

    data["is_weekend"] = (
        data["day_of_week"] >= 5
    ).astype("int8")

    data["time_index"] = (
        data["hour"] * 4
        + data["minute"] // 15
    ).astype("int8")

    return data

In [47]:
# Test the time-feature function

test_features = add_time_features(
    test_long
)

display(
    test_features[
        [
            "timestamp",
            "hour",
            "minute",
            "day_of_week",
            "is_weekend",
            "time_index"
        ]
    ].head(20)
)

    timestamp  hour  minute  day_of_week  is_weekend  time_index
0  2025-04-01     0       0            1           0           0
1  2025-04-01     0       0            1           0           0
2  2025-04-01     0       0            1           0           0
3  2025-04-01     0       0            1           0           0
4  2025-04-01     0       0            1           0           0
5  2025-04-01     0       0            1           0           0
6  2025-04-01     0       0            1           0           0
7  2025-04-01     0       0            1           0           0
8  2025-04-01     0       0            1           0           0
9  2025-04-01     0       0            1           0           0
10 2025-04-01     0       0            1           0           0
11 2025-04-01     0       0            1           0           0
12 2025-04-01     0       0            1           0           0
13 2025-04-01     0       0            1           0           0
14 2025-04-01     0       0            1           0           0
15 2025-04-01     0       0            1           0           0
16 2025-04-01     0       0            1           0           0
17 2025-04-01     0       0            1           0           0
18 2025-04-01     0       0            1           0           0
19 2025-04-01     0       0            1           0           0

In [48]:
# Validate the time-of-day index

print(
    "Minimum time index:",
    test_features["time_index"].min()
)

print(
    "Maximum time index:",
    test_features["time_index"].max()
)

print(
    "Unique time indices:",
    test_features["time_index"].nunique()
)

Minimum time index: 0
Maximum time index: 95
Unique time indices: 96

In [49]:
# Validate weekend flag

print(
    "Unique day_of_week values:",
    test_features["day_of_week"].unique()
)

print(
    "Unique is_weekend values:",
    test_features["is_weekend"].unique()
)

Unique day_of_week values: [1]
Unique is_weekend values: [0]

In [50]:
# Create short-term lag features

def add_short_term_lags(data):
    """
    Add previous 15, 30, 45, and 60 minute traffic volumes.
    """

    data = data.sort_values(
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp"
        ]
    ).copy()

    group_columns = [
        "NB_SCATS_SITE",
        "NB_DETECTOR"
    ]

    for lag in [1, 2, 3, 4]:
        data[f"lag_{lag}"] = (
            data
            .groupby(group_columns)["volume"]
            .shift(lag)
        )

    return data

In [51]:
# Test short-term lag features

test_features = add_short_term_lags(
    test_features
)

display(
    test_features[
        [
            "timestamp",
            "volume",
            "lag_1",
            "lag_2",
            "lag_3",
            "lag_4"
        ]
    ].head(15)
)

                 timestamp  volume  lag_1  lag_2  lag_3  lag_4
0      2025-04-01 00:00:00       2    NaN    NaN    NaN    NaN
50000  2025-04-01 00:15:00       1    2.0    NaN    NaN    NaN
100000 2025-04-01 00:30:00       1    1.0    2.0    NaN    NaN
150000 2025-04-01 00:45:00       2    1.0    1.0    2.0    NaN
200000 2025-04-01 01:00:00       4    2.0    1.0    1.0    2.0
250000 2025-04-01 01:15:00       1    4.0    2.0    1.0    1.0
300000 2025-04-01 01:30:00       4    1.0    4.0    2.0    1.0
350000 2025-04-01 01:45:00       0    4.0    1.0    4.0    2.0
400000 2025-04-01 02:00:00       1    0.0    4.0    1.0    4.0
450000 2025-04-01 02:15:00       1    1.0    0.0    4.0    1.0
500000 2025-04-01 02:30:00       1    1.0    1.0    0.0    4.0
550000 2025-04-01 02:45:00       0    1.0    1.0    1.0    0.0
600000 2025-04-01 03:00:00       1    0.0    1.0    1.0    1.0
650000 2025-04-01 03:15:00       0    1.0    0.0    1.0    1.0
700000 2025-04-01 03:30:00       0    0.0    1.0    0.0    1.0

In [52]:
# Validate short-term lag features

for lag in [1, 2, 3, 4]:

    expected = (
        test_features
        .groupby(
            [
                "NB_SCATS_SITE",
                "NB_DETECTOR"
            ]
        )["volume"]
        .shift(lag)
    )

    mismatch = (
        test_features[f"lag_{lag}"]
        .ne(expected)
        &
        ~(
            test_features[f"lag_{lag}"].isna()
            & expected.isna()
        )
    ).sum()

    print(
        f"lag_{lag} mismatches:",
        mismatch
    )

lag_1 mismatches: 0
lag_2 mismatches: 0
lag_3 mismatches: 0
lag_4 mismatches: 0

In [53]:
# Prepare a history buffer for cross-day temporal features

HISTORY_INTERVALS = 96

history_columns = [
    "NB_SCATS_SITE",
    "NB_DETECTOR",
    "timestamp",
    "volume"
]

history_buffer = (
    test_features[
        history_columns
    ]
    .sort_values(
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp"
        ]
    )
    .copy()
)

print("History buffer shape:")
print(history_buffer.shape)

display(
    history_buffer.head(10)
)

History buffer shape:
(4800000, 4)

        NB_SCATS_SITE  NB_DETECTOR           timestamp  volume
0                 100            1 2025-04-01 00:00:00       2
50000             100            1 2025-04-01 00:15:00       1
100000            100            1 2025-04-01 00:30:00       1
150000            100            1 2025-04-01 00:45:00       2
200000            100            1 2025-04-01 01:00:00       4
250000            100            1 2025-04-01 01:15:00       1
300000            100            1 2025-04-01 01:30:00       4
350000            100            1 2025-04-01 01:45:00       0
400000            100            1 2025-04-01 02:00:00       1
450000            100            1 2025-04-01 02:15:00       1

In [54]:
# Validate the history buffer

print(
    "Unique site-detector combinations:",
    history_buffer[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR"
        ]
    ]
    .drop_duplicates()
    .shape[0]
)

print(
    "Total history rows:",
    len(history_buffer)
)

print(
    "Unique timestamps:",
    history_buffer["timestamp"].nunique()
)

Unique site-detector combinations: 50000
Total history rows: 4800000
Unique timestamps: 96

In [55]:
# Create previous-day traffic history

previous_day = history_buffer.copy()

previous_day["timestamp"] = (
    previous_day["timestamp"]
    + pd.Timedelta(days=1)
)

previous_day = previous_day.rename(
    columns={
        "volume": "lag_96"
    }
)

previous_day = previous_day[
    [
        "NB_SCATS_SITE",
        "NB_DETECTOR",
        "timestamp",
        "lag_96"
    ]
]

display(
    previous_day.head(10)
)

        NB_SCATS_SITE  NB_DETECTOR           timestamp  lag_96
0                 100            1 2025-04-02 00:00:00       2
50000             100            1 2025-04-02 00:15:00       1
100000            100            1 2025-04-02 00:30:00       1
150000            100            1 2025-04-02 00:45:00       2
200000            100            1 2025-04-02 01:00:00       4
250000            100            1 2025-04-02 01:15:00       1
300000            100            1 2025-04-02 01:30:00       4
350000            100            1 2025-04-02 01:45:00       0
400000            100            1 2025-04-02 02:00:00       1
450000            100            1 2025-04-02 02:15:00       1

In [56]:
# Validate the previous-day timestamp mapping

display(
    previous_day[
        [
            "timestamp",
            "lag_96"
        ]
    ].head(20)
)

                 timestamp  lag_96
0      2025-04-02 00:00:00       2
50000  2025-04-02 00:15:00       1
100000 2025-04-02 00:30:00       1
150000 2025-04-02 00:45:00       2
200000 2025-04-02 01:00:00       4
250000 2025-04-02 01:15:00       1
300000 2025-04-02 01:30:00       4
350000 2025-04-02 01:45:00       0
400000 2025-04-02 02:00:00       1
450000 2025-04-02 02:15:00       1
500000 2025-04-02 02:30:00       1
550000 2025-04-02 02:45:00       0
600000 2025-04-02 03:00:00       1
650000 2025-04-02 03:15:00       0
700000 2025-04-02 03:30:00       0
750000 2025-04-02 03:45:00       1
800000 2025-04-02 04:00:00       0
850000 2025-04-02 04:15:00       0
900000 2025-04-02 04:30:00       1
950000 2025-04-02 04:45:00       0

In [57]:
# Create a simulated second day for testing

day_2 = test_features.copy()

day_2["timestamp"] = (
    day_2["timestamp"]
    + pd.Timedelta(days=1)
)

print("Day 2 timestamp range:")
print(day_2["timestamp"].min())
print(day_2["timestamp"].max())

Day 2 timestamp range:
2025-04-02 00:00:00
2025-04-02 23:45:00

In [58]:
# Merge previous-day traffic to create lag_96

day_2 = day_2.merge(
    previous_day,
    on=[
        "NB_SCATS_SITE",
        "NB_DETECTOR",
        "timestamp"
    ],
    how="left"
)

display(
    day_2[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp",
            "volume",
            "lag_96"
        ]
    ].head(20)
)

    NB_SCATS_SITE  NB_DETECTOR           timestamp  volume  lag_96
0             100            1 2025-04-02 00:00:00       2       2
1             100            1 2025-04-02 00:15:00       1       1
2             100            1 2025-04-02 00:30:00       1       1
3             100            1 2025-04-02 00:45:00       2       2
4             100            1 2025-04-02 01:00:00       4       4
5             100            1 2025-04-02 01:15:00       1       1
6             100            1 2025-04-02 01:30:00       4       4
7             100            1 2025-04-02 01:45:00       0       0
8             100            1 2025-04-02 02:00:00       1       1
9             100            1 2025-04-02 02:15:00       1       1
10            100            1 2025-04-02 02:30:00       1       1
11            100            1 2025-04-02 02:45:00       0       0
12            100            1 2025-04-02 03:00:00       1       1
13            100            1 2025-04-02 03:15:00       0       0
14            100            1 2025-04-02 03:30:00       0       0
15            100            1 2025-04-02 03:45:00       1       1
16            100            1 2025-04-02 04:00:00       0       0
17            100            1 2025-04-02 04:15:00       0       0
18            100            1 2025-04-02 04:30:00       1       1
19            100            1 2025-04-02 04:45:00       0       0

In [59]:
# Validate lag_96 after merging previous-day history

print(
    "Rows before merge:",
    len(test_features)
)

print(
    "Rows after merge:",
    len(day_2)
)

print(
    "Missing lag_96:",
    day_2["lag_96"].isna().sum()
)

print(
    "Duplicate site-detector-timestamp keys:",
    day_2.duplicated(
        subset=[
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp"
        ]
    ).sum()
)

Rows before merge: 4800000
Rows after merge: 4800000
Missing lag_96: 0
Duplicate site-detector-timestamp keys: 0

In [60]:
# Manually verify one lag_96 value

example_row = day_2.iloc[0]

site = example_row["NB_SCATS_SITE"]
detector = example_row["NB_DETECTOR"]
timestamp = example_row["timestamp"]

previous_timestamp = timestamp - pd.Timedelta(days=1)

expected_value = test_features[
    (
        test_features["NB_SCATS_SITE"] == site
    )
    &
    (
        test_features["NB_DETECTOR"] == detector
    )
    &
    (
        test_features["timestamp"] == previous_timestamp
    )
]["volume"].iloc[0]

actual_value = example_row["lag_96"]

print("Current timestamp:", timestamp)
print("Previous-day timestamp:", previous_timestamp)

print("\nExpected lag_96:", expected_value)
print("Actual lag_96:", actual_value)

print(
    "\nMatch:",
    expected_value == actual_value
)

Current timestamp: 2025-04-02 00:00:00
Previous-day timestamp: 2025-04-01 00:00:00

Expected lag_96: 2
Actual lag_96: 2

Match: True

In [61]:
# Test short-term lags across a day boundary

previous_day_for_lags = (
    history_buffer[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp",
            "volume"
        ]
    ]
    .copy()
)

combined_history = pd.concat(
    [
        previous_day_for_lags,
        day_2[
            [
                "NB_SCATS_SITE",
                "NB_DETECTOR",
                "timestamp",
                "volume"
            ]
        ]
    ],
    ignore_index=True
)

combined_history = combined_history.sort_values(
    [
        "NB_SCATS_SITE",
        "NB_DETECTOR",
        "timestamp"
    ]
)

for lag in [1, 2, 3, 4]:
    combined_history[f"lag_{lag}"] = (
        combined_history
        .groupby(
            [
                "NB_SCATS_SITE",
                "NB_DETECTOR"
            ]
        )["volume"]
        .shift(lag)
    )

day_2_with_lags = combined_history[
    combined_history["timestamp"] >=
    pd.Timestamp("2025-04-02")
].copy()

display(
    day_2_with_lags[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp",
            "volume",
            "lag_1",
            "lag_2",
            "lag_3",
            "lag_4"
        ]
    ].head(20)
)

,NB_SCATS_SITE,NB_DETECTOR,timestamp,volume,lag_1,lag_2,lag_3,lag_4
4800000,100,1,2025-04-02 00:00:00,2,3.0,3.0,7.0,4.0
4800001,100,1,2025-04-02 00:15:00,1,2.0,3.0,3.0,7.0
4800002,100,1,2025-04-02 00:30:00,1,1.0,2.0,3.0,3.0
4800003,100,1,2025-04-02 00:45:00,2,1.0,1.0,2.0,3.0
4800004,100,1,2025-04-02 01:00:00,4,2.0,1.0,1.0,2.0
4800005,100,1,2025-04-02 01:15:00,1,4.0,2.0,1.0,1.0
4800006,100,1,2025-04-02 01:30:00,4,1.0,4.0,2.0,1.0
4800007,100,1,2025-04-02 01:45:00,0,4.0,1.0,4.0,2.0
4800008,100,1,2025-04-02 02:00:00,1,0.0,4.0,1.0,4.0
4800009,100,1,2025-04-02 02:15:00,1,1.0,0.0,4.0,1.0
4800010,100,1,2025-04-02 02:30:00,1,1.0,1.0,0.0,4.0
4800011,100,1,2025-04-02 02:45:00,0,1.0,1.0,1.0,0.0
4800012,100,1,2025-04-02 03:00:00,1,0.0,1.0,1.0,1.0
4800013,100,1,2025-04-02 03:15:00,0,1.0,0.0,1.0,1.0
4800014,100,1,2025-04-02 03:30:00,0,0.0,1.0,0.0,1.0
4800015,100,1,2025-04-02 03:45:00,1,0.0,0.0,1.0,0.0
4800016,100,1,2025-04-02 04:00:00,0,1.0,0.0,0.0,1.0
4800017,100,1,2025-04-02 04:15:00,0,0.0,1.0,0.0,0.0
4800018,100,1,2025-04-02 04:30:00,1,0.0,0.0,1.0,0.0
4800019,100,1,2025-04-02 04:45:00,0,1.0,0.0,0.0,1.0

In [62]:
# Inspect the first 15-minute interval of Day 2

first_interval = day_2_with_lags[
    day_2_with_lags["timestamp"] ==
    pd.Timestamp("2025-04-02 00:00:00")
]

display(
    first_interval[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp",
            "volume",
            "lag_1",
            "lag_2",
            "lag_3",
            "lag_4"
        ]
    ].head(10)
)

,NB_SCATS_SITE,NB_DETECTOR,timestamp,volume,lag_1,lag_2,lag_3,lag_4
4800000,100,1,2025-04-02,2,3.0,3.0,7.0,4.0
4800096,100,2,2025-04-02,12,8.0,13.0,22.0,29.0
4800192,100,3,2025-04-02,22,28.0,21.0,29.0,48.0
4800288,100,4,2025-04-02,17,17.0,13.0,18.0,22.0
4800384,100,5,2025-04-02,3,2.0,3.0,3.0,14.0
4800480,100,6,2025-04-02,0,0.0,0.0,0.0,0.0
4800576,100,7,2025-04-02,0,0.0,0.0,0.0,0.0
4800672,100,8,2025-04-02,0,0.0,0.0,0.0,0.0
4800768,100,9,2025-04-02,0,0.0,0.0,0.0,0.0
4800864,100,10,2025-04-02,0,0.0,0.0,0.0,0.0

In [63]:
# Validate lag_1 to lag_4 at the Day 2 boundary

boundary = day_2_with_lags[
    day_2_with_lags["timestamp"]
    == pd.Timestamp("2025-04-02 00:00:00")
].copy()

# Create expected values using timestamp-based lookup
expected_boundary = history_buffer[
    history_buffer["timestamp"].isin(
        [
            pd.Timestamp("2025-04-01 23:45:00"),
            pd.Timestamp("2025-04-01 23:30:00"),
            pd.Timestamp("2025-04-01 23:15:00"),
            pd.Timestamp("2025-04-01 23:00:00")
        ]
    )
].copy()

# Pivot previous observations into lag columns
expected_boundary["lag_number"] = (
    (
        pd.Timestamp("2025-04-02 00:00:00")
        - expected_boundary["timestamp"]
    ).dt.total_seconds() // 900
).astype(int)

expected_boundary = expected_boundary.pivot(
    index=[
        "NB_SCATS_SITE",
        "NB_DETECTOR"
    ],
    columns="lag_number",
    values="volume"
).reset_index()

expected_boundary = expected_boundary.rename(
    columns={
        1: "expected_lag_1",
        2: "expected_lag_2",
        3: "expected_lag_3",
        4: "expected_lag_4"
    }
)

# Merge expected values with actual values
validation = boundary.merge(
    expected_boundary,
    on=[
        "NB_SCATS_SITE",
        "NB_DETECTOR"
    ],
    how="left"
)

for lag in [1, 2, 3, 4]:

    mismatch = (
        ~np.isclose(
            validation[f"lag_{lag}"],
            validation[f"expected_lag_{lag}"],
            equal_nan=True
        )
    ).sum()

    print(
        f"lag_{lag} boundary mismatches:",
        mismatch
    )

lag_1 boundary mismatches: 0
lag_2 boundary mismatches: 0
lag_3 boundary mismatches: 0
lag_4 boundary mismatches: 0

In [64]:
# Create historical rolling features

def add_rolling_features(data):
    """
    Create rolling traffic statistics using only previous observations.
    """

    data = data.sort_values(
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp"
        ]
    ).copy()

    group_columns = [
        "NB_SCATS_SITE",
        "NB_DETECTOR"
    ]

    grouped_volume = (
        data
        .groupby(group_columns)["volume"]
    )

    data["rolling_mean_4"] = (
        grouped_volume
        .shift(1)
        .groupby(
            [
                data["NB_SCATS_SITE"],
                data["NB_DETECTOR"]
            ]
        )
        .rolling(4)
        .mean()
        .reset_index(
            level=[0, 1],
            drop=True
        )
    )

    data["rolling_std_4"] = (
        grouped_volume
        .shift(1)
        .groupby(
            [
                data["NB_SCATS_SITE"],
                data["NB_DETECTOR"]
            ]
        )
        .rolling(4)
        .std()
        .reset_index(
            level=[0, 1],
            drop=True
        )
    )

    data["rolling_mean_8"] = (
        grouped_volume
        .shift(1)
        .groupby(
            [
                data["NB_SCATS_SITE"],
                data["NB_DETECTOR"]
            ]
        )
        .rolling(8)
        .mean()
        .reset_index(
            level=[0, 1],
            drop=True
        )
    )

    return data

In [65]:
# Test rolling features

rolling_test = add_rolling_features(
    day_2_with_lags
)

display(
    rolling_test[
        [
            "timestamp",
            "volume",
            "rolling_mean_4",
            "rolling_std_4",
            "rolling_mean_8"
        ]
    ].head(15)
)

,timestamp,volume,rolling_mean_4,rolling_std_4,rolling_mean_8
4800000,2025-04-02 00:00:00,2,NaN,NaN,NaN
4800001,2025-04-02 00:15:00,1,NaN,NaN,NaN
4800002,2025-04-02 00:30:00,1,NaN,NaN,NaN
4800003,2025-04-02 00:45:00,2,NaN,NaN,NaN
4800004,2025-04-02 01:00:00,4,1.50,0.577350,NaN
4800005,2025-04-02 01:15:00,1,2.00,1.414214,NaN
4800006,2025-04-02 01:30:00,4,2.00,1.414214,NaN
4800007,2025-04-02 01:45:00,0,2.75,1.500000,NaN
4800008,2025-04-02 02:00:00,1,2.25,2.061553,1.875
4800009,2025-04-02 02:15:00,1,1.50,1.732051,1.750
4800010,2025-04-02 02:30:00,1,1.50,1.732051,1.750
4800011,2025-04-02 02:45:00,0,0.75,0.500000,1.750
4800012,2025-04-02 03:00:00,1,0.75,0.500000,1.500
4800013,2025-04-02 03:15:00,0,0.75,0.500000,1.125
4800014,2025-04-02 03:30:00,0,0.50,0.577350,1.000

In [66]:
# Verify rolling mean uses only historical observations

example = rolling_test[
    rolling_test["timestamp"]
    == pd.Timestamp("2025-04-02 01:00:00")
].iloc[0]

site = example["NB_SCATS_SITE"]
detector = example["NB_DETECTOR"]

previous_values = (
    rolling_test[
        (rolling_test["NB_SCATS_SITE"] == site)
        &
        (rolling_test["NB_DETECTOR"] == detector)
        &
        (
            rolling_test["timestamp"]
            < pd.Timestamp("2025-04-02 01:00:00")
        )
    ]
    .sort_values("timestamp")
    ["volume"]
    .tail(4)
)

expected_mean = previous_values.mean()

print("Previous 4 values:")
print(previous_values.tolist())

print("\nExpected rolling mean:", expected_mean)
print(
    "Actual rolling mean:",
    example["rolling_mean_4"]
)

print(
    "\nMatch:",
    np.isclose(
        expected_mean,
        example["rolling_mean_4"]
    )
)

Previous 4 values:
[2, 1, 1, 2]

Expected rolling mean: 1.5
Actual rolling mean: 1.5

Match: True

In [67]:
# Create the next 15-minute traffic target

def add_target(data):
    """
    Create the next 15-minute traffic volume as the target.
    """

    data = data.sort_values(
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp"
        ]
    ).copy()

    group_columns = [
        "NB_SCATS_SITE",
        "NB_DETECTOR"
    ]

    data["target"] = (
        data
        .groupby(group_columns)["volume"]
        .shift(-1)
    )

    return data

In [68]:
# Test the target function

target_test = add_target(
    rolling_test
)

display(
    target_test[
        [
            "timestamp",
            "volume",
            "target"
        ]
    ].head(15)
)

                  timestamp  volume  target
4800000 2025-04-02 00:00:00       2     1.0
4800001 2025-04-02 00:15:00       1     1.0
4800002 2025-04-02 00:30:00       1     2.0
4800003 2025-04-02 00:45:00       2     4.0
4800004 2025-04-02 01:00:00       4     1.0
4800005 2025-04-02 01:15:00       1     4.0
4800006 2025-04-02 01:30:00       4     0.0
4800007 2025-04-02 01:45:00       0     1.0
4800008 2025-04-02 02:00:00       1     1.0
4800009 2025-04-02 02:15:00       1     1.0
4800010 2025-04-02 02:30:00       1     0.0
4800011 2025-04-02 02:45:00       0     1.0
4800012 2025-04-02 03:00:00       1     0.0
4800013 2025-04-02 03:15:00       0     0.0
4800014 2025-04-02 03:30:00       0     1.0

In [69]:
# Manually validate one target value

example = target_test[
    target_test["timestamp"]
    == pd.Timestamp("2025-04-02 01:00:00")
].iloc[0]

site = example["NB_SCATS_SITE"]
detector = example["NB_DETECTOR"]

next_value = target_test[
    (
        target_test["NB_SCATS_SITE"] == site
    )
    &
    (
        target_test["NB_DETECTOR"] == detector
    )
    &
    (
        target_test["timestamp"]
        == pd.Timestamp("2025-04-02 01:15:00")
    )
]["volume"].iloc[0]

print("Current timestamp:", example["timestamp"])
print("Current volume:", example["volume"])

print("\nExpected target:", next_value)
print("Actual target:", example["target"])

print(
    "\nMatch:",
    next_value == example["target"]
)

Current timestamp: 2025-04-02 01:00:00
Current volume: 4

Expected target: 1
Actual target: 1.0

Match: True

In [70]:
# Check target missing values

target_missing = (
    target_test["target"]
    .isna()
    .sum()
)

print(
    "Missing target values:",
    target_missing
)

print(
    "Total site-detector combinations:",
    target_test[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR"
        ]
    ]
    .drop_duplicates()
    .shape[0]
)

Missing target values: 50000
Total site-detector combinations: 50000

In [71]:
# Create next-day data for target validation

next_day_for_target = test_features.copy()

next_day_for_target["timestamp"] = (
    next_day_for_target["timestamp"]
    + pd.Timedelta(days=1)
)

next_day_for_target = next_day_for_target[
    [
        "NB_SCATS_SITE",
        "NB_DETECTOR",
        "timestamp",
        "volume"
    ]
].copy()

print("Next-day timestamp range:")
print(next_day_for_target["timestamp"].min())
print(next_day_for_target["timestamp"].max())

Next-day timestamp range:
2025-04-02 00:00:00
2025-04-02 23:45:00

In [72]:
# Validate target across the day boundary

day_1_boundary = target_test[
    target_test["timestamp"]
    == pd.Timestamp("2025-04-01 23:45:00")
].copy()

day_1_boundary = day_1_boundary.merge(
    next_day_for_target[
        next_day_for_target["timestamp"]
        == pd.Timestamp("2025-04-02 00:00:00")
    ][
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "volume"
        ]
    ].rename(
        columns={
            "volume": "expected_target"
        }
    ),
    on=[
        "NB_SCATS_SITE",
        "NB_DETECTOR"
    ],
    how="left"
)

display(
    day_1_boundary[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp",
            "target",
            "expected_target"
        ]
    ].head(10)
)

Empty DataFrame
Columns: [NB_SCATS_SITE, NB_DETECTOR, timestamp, target, expected_target]
Index: []

In [73]:
# Assign the next day's first interval as the boundary target

day_1_boundary["boundary_target"] = (
    day_1_boundary["expected_target"]
)

display(
    day_1_boundary[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp",
            "boundary_target"
        ]
    ].head(10)
)

Empty DataFrame
Columns: [NB_SCATS_SITE, NB_DETECTOR, timestamp, boundary_target]
Index: []

In [74]:
# Validate the Day 1 -> Day 2 target mapping

target_boundary_mismatch = (
    day_1_boundary["boundary_target"]
    .isna()
    .sum()
)

print(
    "Missing boundary targets:",
    target_boundary_mismatch
)

Missing boundary targets: 0

In [75]:
# Define the final modeling columns

IDENTIFIER_COLUMNS = [
    "NB_SCATS_SITE",
    "NB_DETECTOR"
]

TIME_COLUMNS = [
    "timestamp"
]

FEATURE_COLUMNS = [
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_4",
    "lag_96",
    "rolling_mean_4",
    "rolling_std_4",
    "rolling_mean_8",
    "hour",
    "minute",
    "day_of_week",
    "is_weekend",
    "time_index"
]

TARGET_COLUMN = "target"

FINAL_COLUMNS = (
    IDENTIFIER_COLUMNS
    + TIME_COLUMNS
    + FEATURE_COLUMNS
    + [TARGET_COLUMN]
)

print("Number of final columns:", len(FINAL_COLUMNS))

print("\nFinal columns:")
for column in FINAL_COLUMNS:
    print("-", column)

Number of final columns: 17

Final columns:
- NB_SCATS_SITE
- NB_DETECTOR
- timestamp
- lag_1
- lag_2
- lag_3
- lag_4
- lag_96
- rolling_mean_4
- rolling_std_4
- rolling_mean_8
- hour
- minute
- day_of_week
- is_weekend
- time_index
- target

In [76]:
# Build a complete feature sample for validation

# Start with the rolling-feature dataset
modeling_sample = rolling_test.copy()

# Add calendar and time features
modeling_sample = add_time_features(
    modeling_sample
)

# Add lag_96 from the validated previous-day mapping
lag_96_data = day_2[
    [
        "NB_SCATS_SITE",
        "NB_DETECTOR",
        "timestamp",
        "lag_96"
    ]
].copy()

modeling_sample = modeling_sample.merge(
    lag_96_data,
    on=[
        "NB_SCATS_SITE",
        "NB_DETECTOR",
        "timestamp"
    ],
    how="left"
)

# Add the next 15-minute target
modeling_sample = add_target(
    modeling_sample
)

print("Modeling sample shape:")
print(modeling_sample.shape)

display(
    modeling_sample.head()
)

Modeling sample shape:
(4800000, 18)

,NB_SCATS_SITE,NB_DETECTOR,timestamp,volume,lag_1,lag_2,lag_3,lag_4,rolling_mean_4,rolling_std_4,rolling_mean_8,hour,minute,day_of_week,is_weekend,time_index,lag_96,target
0,100,1,2025-04-02 00:00:00,2,3.0,3.0,7.0,4.0,NaN,NaN,NaN,0,0,2,0,0,2,1.0
1,100,1,2025-04-02 00:15:00,1,2.0,3.0,3.0,7.0,NaN,NaN,NaN,0,15,2,0,1,1,1.0
2,100,1,2025-04-02 00:30:00,1,1.0,2.0,3.0,3.0,NaN,NaN,NaN,0,30,2,0,2,1,2.0
3,100,1,2025-04-02 00:45:00,2,1.0,1.0,2.0,3.0,NaN,NaN,NaN,0,45,2,0,3,2,4.0
4,100,1,2025-04-02 01:00:00,4,2.0,1.0,1.0,2.0,1.5,0.57735,NaN,1,0,2,0,4,4,1.0

In [77]:
# Inspect final modeling columns

print("Available columns:")

for column in modeling_sample.columns:
    print("-", column)

print(
    "\nNumber of columns:",
    len(modeling_sample.columns)
)

Available columns:
- NB_SCATS_SITE
- NB_DETECTOR
- timestamp
- volume
- lag_1
- lag_2
- lag_3
- lag_4
- rolling_mean_4
- rolling_std_4
- rolling_mean_8
- hour
- minute
- day_of_week
- is_weekend
- time_index
- lag_96
- target

Number of columns: 18

In [78]:
# Check missing values in the final modeling sample

missing_summary = (
    modeling_sample
    .isna()
    .sum()
    .sort_values(ascending=False)
)

display(
    missing_summary[
        missing_summary > 0
    ]
)

rolling_mean_8    400000
rolling_mean_4    200000
rolling_std_4     200000
target             50000
dtype: int64

In [79]:
# Select only the final modeling columns

modeling_data = modeling_sample[
    FINAL_COLUMNS
].copy()

print("Final modeling data shape:")
print(modeling_data.shape)

print("\nFinal columns:")
print(modeling_data.columns.tolist())

Final modeling data shape:
(4800000, 17)

Final columns:
['NB_SCATS_SITE', 'NB_DETECTOR', 'timestamp', 'lag_1', 'lag_2', 'lag_3', 'lag_4', 'lag_96', 'rolling_mean_4', 'rolling_std_4', 'rolling_mean_8', 'hour', 'minute', 'day_of_week', 'is_weekend', 'time_index', 'target']

In [80]:
# Validate final modeling columns

missing_columns = [
    column
    for column in FINAL_COLUMNS
    if column not in modeling_data.columns
]

extra_columns = [
    column
    for column in modeling_data.columns
    if column not in FINAL_COLUMNS
]

print("Missing expected columns:")
print(missing_columns)

print("\nUnexpected extra columns:")
print(extra_columns)

print("\nColumn validation passed:",
      len(missing_columns) == 0 and len(extra_columns) == 0)

Missing expected columns:
[]

Unexpected extra columns:
[]

Column validation passed: True

In [81]:
# Inspect final modeling data types

print("Final modeling data types:")

display(
    modeling_data.dtypes.to_frame(
        name="dtype"
    )
)

Final modeling data types:

                         dtype
NB_SCATS_SITE            int64
NB_DETECTOR              int64
timestamp       datetime64[us]
lag_1                  float64
lag_2                  float64
lag_3                  float64
lag_4                  float64
lag_96                   int64
rolling_mean_4         float64
rolling_std_4          float64
rolling_mean_8         float64
hour                     int32
minute                   int32
day_of_week              int32
is_weekend                int8
time_index                int8
target                 float64

In [82]:
# Final missing-value summary

missing_summary = (
    modeling_data
    .isna()
    .sum()
    .sort_values(
        ascending=False
    )
)

display(
    missing_summary[
        missing_summary > 0
    ]
)

rolling_mean_8    400000
rolling_std_4     200000
rolling_mean_4    200000
target             50000
dtype: int64

In [83]:
# Final dtype check

print(modeling_data.dtypes)

NB_SCATS_SITE              int64
NB_DETECTOR                int64
timestamp         datetime64[us]
lag_1                    float64
lag_2                    float64
lag_3                    float64
lag_4                    float64
lag_96                     int64
rolling_mean_4           float64
rolling_std_4            float64
rolling_mean_8           float64
hour                       int32
minute                     int32
day_of_week                int32
is_weekend                  int8
time_index                  int8
target                   float64
dtype: object

In [84]:
# Final missing-value check

missing_summary = (
    modeling_data
    .isna()
    .sum()
)

print(missing_summary[missing_summary > 0])

rolling_mean_4    200000
rolling_std_4     200000
rolling_mean_8    400000
target             50000
dtype: int64

## Production Feature Engineering

The feature logic has been validated on a controlled sample.

The full dataset is approximately 10 GB, so the production pipeline will process the raw CSV incrementally rather than loading the complete dataset into memory.

The engineered data will be written incrementally to disk, allowing the feature-engineering stage to remain memory-efficient.

In [85]:
# Production processing configuration

PRODUCTION_CHUNK_SIZE = 50_000

print(
    "Production chunk size:",
    PRODUCTION_CHUNK_SIZE
)

Production chunk size: 50000

In [86]:
# Define the directory for engineered data

FEATURED_DATA_DIR = PROCESSED_DATA_DIR / "featured"

FEATURED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(
    "Feature output directory:"
)

print(FEATURED_DATA_DIR)

Feature output directory:
c:\Users\Aditya\Smart_traffic_management\data\processed\featured

In [87]:
# Columns required from the raw CSV

PRODUCTION_INPUT_COLUMNS = [
    "NB_SCATS_SITE",
    "QT_INTERVAL_COUNT",
    "NB_DETECTOR",
    "NM_REGION"
] + traffic_columns

print(
    "Raw columns required:",
    len(PRODUCTION_INPUT_COLUMNS)
)

print(
    "\nTraffic columns:",
    len(traffic_columns)
)

Raw columns required: 100

Traffic columns: 96

In [88]:
# Clean previous feature-engineering output before a fresh run

def clear_feature_output(output_dir):
    """
    Remove previously generated feature files.
    """

    existing_files = list(
        output_dir.glob("*.parquet")
    )

    for file_path in existing_files:
        file_path.unlink()

    print(
        f"Removed {len(existing_files)} existing Parquet files."
    )


clear_feature_output(
    FEATURED_DATA_DIR
)

Removed 0 existing Parquet files.

In [89]:
# Test the production CSV reader

production_test = pd.read_csv(
    DATA_FILE,
    usecols=PRODUCTION_INPUT_COLUMNS,
    nrows=PRODUCTION_CHUNK_SIZE
)

print("Production test shape:")
print(production_test.shape)

print("\nMemory usage:")
memory_mb = (
    production_test.memory_usage(deep=True).sum()
    / (1024 ** 2)
)

print(f"{memory_mb:.2f} MB")

Production test shape:
(50000, 100)

Memory usage:
38.77 MB

In [90]:
# Convert the production date column

production_test["QT_INTERVAL_COUNT"] = pd.to_datetime(
    production_test["QT_INTERVAL_COUNT"]
)

print(
    "QT_INTERVAL_COUNT dtype:",
    production_test["QT_INTERVAL_COUNT"].dtype
)

print(
    "First date:",
    production_test["QT_INTERVAL_COUNT"].min()
)

print(
    "Last date:",
    production_test["QT_INTERVAL_COUNT"].max()
)

QT_INTERVAL_COUNT dtype: datetime64[us]
First date: 2025-04-01 00:00:00
Last date: 2025-04-01 00:00:00

In [91]:
# Verify production input columns

missing_input_columns = [
    column
    for column in PRODUCTION_INPUT_COLUMNS
    if column not in production_test.columns
]

print(
    "Missing required columns:",
    missing_input_columns
)

print(
    "Number of loaded columns:",
    len(production_test.columns)
)

Missing required columns: []
Number of loaded columns: 100

In [92]:
# Identify the date contained in the production test chunk

test_date = (
    production_test["QT_INTERVAL_COUNT"]
    .dt.normalize()
    .iloc[0]
)

test_day = production_test[
    production_test["QT_INTERVAL_COUNT"].dt.normalize()
    == test_date
].copy()

print("Test date:")
print(test_date)

print("\nRows for test date:")
print(len(test_day))

print("\nDate range:")
print(
    test_day["QT_INTERVAL_COUNT"].min(),
    "to",
    test_day["QT_INTERVAL_COUNT"].max()
)

Test date:
2025-04-01 00:00:00

Rows for test date:
50000

Date range:
2025-04-01 00:00:00 to 2025-04-01 00:00:00

In [93]:
# Reshape the production test date

production_long_test = reshape_daily_traffic(
    test_day
)

print("Long-format shape:")
print(production_long_test.shape)

print("\nColumns:")
print(
    production_long_test.columns.tolist()
)

Long-format shape:
(4800000, 9)

Columns:
['NB_SCATS_SITE', 'NB_DETECTOR', 'QT_INTERVAL_COUNT', 'NM_REGION', 'interval', 'volume', 'minutes_after_midnight', 'time', 'timestamp']

In [94]:
# Add calendar and time features

production_long_test = add_time_features(
    production_long_test
)

print("Shape after time features:")
print(production_long_test.shape)

display(
    production_long_test[
        [
            "timestamp",
            "hour",
            "minute",
            "day_of_week",
            "is_weekend",
            "time_index"
        ]
    ].head()
)

Shape after time features:
(4800000, 14)

   timestamp  hour  minute  day_of_week  is_weekend  time_index
0 2025-04-01     0       0            1           0           0
1 2025-04-01     0       0            1           0           0
2 2025-04-01     0       0            1           0           0
3 2025-04-01     0       0            1           0           0
4 2025-04-01     0       0            1           0           0

In [95]:
# Add short-term lag features

production_long_test = add_short_term_lags(
    production_long_test
)

print("Shape after lag features:")
print(production_long_test.shape)

display(
    production_long_test[
        [
            "timestamp",
            "volume",
            "lag_1",
            "lag_2",
            "lag_3",
            "lag_4"
        ]
    ].head(10)
)

Shape after lag features:
(4800000, 18)

                 timestamp  volume  lag_1  lag_2  lag_3  lag_4
0      2025-04-01 00:00:00       2    NaN    NaN    NaN    NaN
50000  2025-04-01 00:15:00       1    2.0    NaN    NaN    NaN
100000 2025-04-01 00:30:00       1    1.0    2.0    NaN    NaN
150000 2025-04-01 00:45:00       2    1.0    1.0    2.0    NaN
200000 2025-04-01 01:00:00       4    2.0    1.0    1.0    2.0
250000 2025-04-01 01:15:00       1    4.0    2.0    1.0    1.0
300000 2025-04-01 01:30:00       4    1.0    4.0    2.0    1.0
350000 2025-04-01 01:45:00       0    4.0    1.0    4.0    2.0
400000 2025-04-01 02:00:00       1    0.0    4.0    1.0    4.0
450000 2025-04-01 02:15:00       1    1.0    0.0    4.0    1.0

In [96]:
# Process one complete day's traffic data

def process_daily_features(day_data):
    """
    Convert one day's raw SCATS data into engineered features.

    This function assumes that day_data contains a complete date.
    Cross-day features such as lag_96 and the final target boundary
    will be handled separately by the production pipeline.
    """

    # Wide format -> timestamped long format
    data = reshape_daily_traffic(day_data)

    # Calendar and time-of-day features
    data = add_time_features(data)

    # Short-term historical features
    data = add_short_term_lags(data)

    # Rolling historical features
    data = add_rolling_features(data)

    # Next 15-minute target
    data = add_target(data)

    return data

In [97]:
# Test the complete daily feature function

daily_feature_test = process_daily_features(
    test_day
)

print("Daily feature test shape:")
print(daily_feature_test.shape)

print("\nColumns:")
print(
    daily_feature_test.columns.tolist()
)

Daily feature test shape:
(4800000, 22)

Columns:
['NB_SCATS_SITE', 'NB_DETECTOR', 'QT_INTERVAL_COUNT', 'NM_REGION', 'interval', 'volume', 'minutes_after_midnight', 'time', 'timestamp', 'hour', 'minute', 'day_of_week', 'is_weekend', 'time_index', 'lag_1', 'lag_2', 'lag_3', 'lag_4', 'rolling_mean_4', 'rolling_std_4', 'rolling_mean_8', 'target']

In [98]:
# Validate the complete daily feature output

required_daily_features = [
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_4",
    "rolling_mean_4",
    "rolling_std_4",
    "rolling_mean_8",
    "hour",
    "minute",
    "day_of_week",
    "is_weekend",
    "time_index",
    "target"
]

missing_features = [
    feature
    for feature in required_daily_features
    if feature not in daily_feature_test.columns
]

print("Missing daily features:")
print(missing_features)

print(
    "\nDaily feature validation:",
    len(missing_features) == 0
)

Missing daily features:
[]

Daily feature validation: True

In [99]:
# Check memory usage of the daily engineered data

memory_mb = (
    daily_feature_test
    .memory_usage(deep=True)
    .sum()
    / (1024 ** 2)   
)

print(
    f"Daily engineered data memory: {memory_mb:.2f} MB"
)

print(
    "\nRows:",
    len(daily_feature_test)
)

Daily engineered data memory: 682.64 MB

Rows: 4800000

In [100]:
# Keep only the within-day modeling columns for memory testing

WITHIN_DAY_COLUMNS = [
    column
    for column in FINAL_COLUMNS
    if column != "lag_96"
]

daily_modeling_test = daily_feature_test[
    WITHIN_DAY_COLUMNS
].copy()

print("Daily modeling data shape:")
print(daily_modeling_test.shape)

memory_mb = (
    daily_modeling_test
    .memory_usage(deep=True)
    .sum()
    / (1024 ** 2)
)

print(
    f"\nDaily modeling data memory: {memory_mb:.2f} MB"
)

print("\nColumns:")
print(
    daily_modeling_test.columns.tolist()
)

Daily modeling data shape:
(4800000, 16)

Daily modeling data memory: 503.54 MB

Columns:
['NB_SCATS_SITE', 'NB_DETECTOR', 'timestamp', 'lag_1', 'lag_2', 'lag_3', 'lag_4', 'rolling_mean_4', 'rolling_std_4', 'rolling_mean_8', 'hour', 'minute', 'day_of_week', 'is_weekend', 'time_index', 'target']

In [101]:
# Check rows with complete within-day features

complete_rows = (
    daily_modeling_test
    .notna()
    .all(axis=1)
)

print(
    "Total rows:",
    len(daily_modeling_test)
)

print(
    "Complete within-day rows:",
    complete_rows.sum()
)

print(
    "Rows with missing values:",
    (~complete_rows).sum()
)

Total rows: 4800000
Complete within-day rows: 4350000
Rows with missing values: 450000

In [102]:
# Calculate the percentage of complete within-day rows

usable_percentage = (
    complete_rows.mean() * 100
)

print(
    f"Usable within-day rows: "
    f"{usable_percentage:.2f}%"
)

Usable within-day rows: 90.62%

In [103]:
# Iterate through the raw CSV while keeping complete dates together

def iter_complete_days(
    file_path,
    usecols,
    chunksize=50_000
):
    """
    Read the raw CSV in chunks while yielding complete dates.

    A date may span multiple CSV chunks, so the current date
    is carried forward until all of its rows have been read.
    """

    reader = pd.read_csv(
        file_path,
        usecols=usecols,
        chunksize=chunksize
    )

    pending_day = None

    for chunk in reader:

        chunk["QT_INTERVAL_COUNT"] = pd.to_datetime(
            chunk["QT_INTERVAL_COUNT"]
        )

        chunk["date"] = (
            chunk["QT_INTERVAL_COUNT"]
            .dt.normalize()
        )

        dates = chunk["date"].drop_duplicates().tolist()

        for current_date in dates:

            current_part = chunk[
                chunk["date"] == current_date
            ].copy()

            if pending_day is None:

                pending_day = current_part

            else:

                pending_day = pd.concat(
                    [
                        pending_day,
                        current_part
                    ],
                    ignore_index=True
                )

            # If this is not the last date in the chunk,
            # the current date is complete within this chunk.
            if current_date != dates[-1]:

                yield pending_day.drop(
                    columns="date"
                )

                pending_day = None

    # Yield the final pending date
    if pending_day is not None:

        yield pending_day.drop(
            columns="date"
        )

In [104]:
# Test the complete-day iterator on a small portion of the dataset

day_iterator = iter_complete_days(
    DATA_FILE,
    PRODUCTION_INPUT_COLUMNS,
    chunksize=50_000
)

first_day = next(day_iterator)

print("First complete day shape:")
print(first_day.shape)

print("\nFirst date:")
print(
    first_day["QT_INTERVAL_COUNT"].min()
)

print("\nLast date:")
print(
    first_day["QT_INTERVAL_COUNT"].max()
)

First complete day shape:
(114025, 100)

First date:
2025-04-01 00:00:00

Last date:
2025-04-01 00:00:00

In [105]:
# Verify that the yielded data contains exactly one date

unique_dates = (
    first_day["QT_INTERVAL_COUNT"]
    .dt.normalize()
    .nunique()
)

print(
    "Unique dates in yielded data:",
    unique_dates
)

print(
    "Complete-day validation:",
    unique_dates == 1
)

Unique dates in yielded data: 1
Complete-day validation: True

In [106]:
# Get the next complete day from the iterator

second_day = next(day_iterator)

print("Second complete day shape:")
print(second_day.shape)

print("\nFirst date:")
print(
    second_day["QT_INTERVAL_COUNT"].min()
)

print("\nLast date:")
print(
    second_day["QT_INTERVAL_COUNT"].max()
)

print(
    "\nUnique dates:",
    second_day["QT_INTERVAL_COUNT"]
    .dt.normalize()
    .nunique()
)

Second complete day shape:
(114017, 100)

First date:
2025-04-02 00:00:00

Last date:
2025-04-02 00:00:00

Unique dates: 1

In [107]:
# Check chronological order of the yielded days

first_date = (
    first_day["QT_INTERVAL_COUNT"]
    .dt.normalize()
    .iloc[0]
)

second_date = (
    second_day["QT_INTERVAL_COUNT"]
    .dt.normalize()
    .iloc[0]
)

print("First yielded date:", first_date)
print("Second yielded date:", second_date)

print(
    "\nDays between them:",
    (second_date - first_date).days
)

First yielded date: 2025-04-01 00:00:00
Second yielded date: 2025-04-02 00:00:00

Days between them: 1

In [108]:
# Validate the date structure of the two test days

for day_number, day_data in enumerate(
    [first_day, second_day],
    start=1
):

    unique_dates = (
        day_data["QT_INTERVAL_COUNT"]
        .dt.normalize()
        .nunique()
    )

    print(
        f"Day {day_number}: "
        f"{unique_dates} unique date(s)"
    )

Day 1: 1 unique date(s)
Day 2: 1 unique date(s)

In [109]:
# Check site-detector-date uniqueness

key_columns = [
    "NB_SCATS_SITE",
    "NB_DETECTOR",
    "QT_INTERVAL_COUNT"
]

duplicate_keys = (
    first_day
    .duplicated(
        subset=key_columns
    )
    .sum()
)

print(
    "Duplicate site-detector-date rows:",
    duplicate_keys
)

Duplicate site-detector-date rows: 0

In [110]:
# Inspect the number of raw records per site-detector

records_per_detector = (
    first_day
    .groupby(
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR"
        ]
    )
    .size()
)

print(
    "Number of site-detector combinations:",
    records_per_detector.size
)

print("\nRecord-count distribution:")

display(
    records_per_detector
    .value_counts()
    .sort_index()
)

Number of site-detector combinations: 114025

Record-count distribution:

1    114025
Name: count, dtype: int64

In [111]:
# Number of raw site-detector records processed at one time

FEATURE_BATCH_SIZE = 5_000

print(
    "Feature batch size:",
    FEATURE_BATCH_SIZE
)

Feature batch size: 5000

In [112]:
# Split a complete day's raw data into manageable batches

def iter_day_batches(
    day_data,
    batch_size=FEATURE_BATCH_SIZE
):
    """
    Yield smaller batches from one complete day's raw data.
    """

    total_rows = len(day_data)

    for start in range(
        0,
        total_rows,
        batch_size
    ):
        end = min(
            start + batch_size,
            total_rows
        )

        yield day_data.iloc[start:end].copy()

In [113]:
# Test batch sizes on the first complete day

batch_sizes = []

for batch in iter_day_batches(first_day):

    batch_sizes.append(
        len(batch)
    )

print(
    "Number of batches:",
    len(batch_sizes)
)

print(
    "Batch sizes:",
    batch_sizes[:10]
)

print(
    "\nTotal rows across batches:",
    sum(batch_sizes)
)

print(
    "Original day rows:",
    len(first_day)
)

Number of batches: 23
Batch sizes: [5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000]

Total rows across batches: 114025
Original day rows: 114025

In [114]:
# Validate that batching preserves every raw record

original_keys = set(
    zip(
        first_day["NB_SCATS_SITE"],
        first_day["NB_DETECTOR"]
    )
)

batched_keys = set()

for batch in iter_day_batches(first_day):

    batched_keys.update(
        zip(
            batch["NB_SCATS_SITE"],
            batch["NB_DETECTOR"]
        )
    )

print(
    "Original site-detector records:",
    len(original_keys)
)

print(
    "Batched site-detector records:",
    len(batched_keys)
)

print(
    "Records lost:",
    len(original_keys - batched_keys)
)

print(
    "Records duplicated:",
    len(batched_keys - original_keys)
)

Original site-detector records: 114025
Batched site-detector records: 114025
Records lost: 0
Records duplicated: 0

In [115]:
# Prepare previous-day traffic history

def prepare_day_history(day_data):
    """
    Keep only the information required to calculate lag_96
    for the following day.
    """

    history = reshape_daily_traffic(
        day_data
    )

    history = history[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp",
            "volume"
        ]
    ].copy()

    return history

In [116]:
# Create a compact previous-day history

def prepare_compact_history(day_data):
    """
    Prepare a compact representation of the day's traffic
    for calculating lag_96 on the following day.
    """

    history = day_data[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR"
        ] + traffic_columns
    ].copy()

    return history

In [117]:
# Compare the compact history representation

compact_history = prepare_compact_history(
    first_day
)

print("Compact history shape:")
print(compact_history.shape)

compact_memory = (
    compact_history
    .memory_usage(deep=True)
    .sum()
    / (1024 ** 2)
)

print(
    f"\nCompact history memory: "
    f"{compact_memory:.2f} MB"
)

Compact history shape:
(114025, 98)

Compact history memory: 85.25 MB

In [118]:
# Validate the compact history columns

missing_traffic_columns = [
    column
    for column in traffic_columns
    if column not in compact_history.columns
]

print(
    "Missing traffic columns:",
    missing_traffic_columns
)

print(
    "\nNumber of traffic intervals:",
    len(traffic_columns)
)

print(
    "Compact history validation:",
    len(missing_traffic_columns) == 0
)

Missing traffic columns: []

Number of traffic intervals: 96
Compact history validation: True

In [119]:
# Add previous-day traffic values as lag_96

def add_lag_96_to_day(
    current_day,
    previous_day
):
    """
    Add previous-day same-interval traffic as lag_96.

    The current and previous day are matched using:
    SCATS site + detector.
    """

    current = current_day.copy()

    previous = prepare_compact_history(
        previous_day
    )

    # Keep only the columns needed for the join
    previous = previous[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR"
        ] + traffic_columns
    ]

    # Rename previous-day interval columns
    # so they can be distinguished after the merge.
    previous = previous.rename(
        columns={
            column: f"lag96_{column}"
            for column in traffic_columns
        }
    )

    current = current.merge(
        previous,
        on=[
            "NB_SCATS_SITE",
            "NB_DETECTOR"
        ],
        how="left",
        validate="one_to_one"
    )

    return current

In [120]:
# Test lag_96 preparation using two consecutive days

current_day_test = add_lag_96_to_day(
    second_day,
    first_day
)

print("Current day shape:")
print(current_day_test.shape)

print("\nExpected current-day rows:")
print(len(second_day))

print("\nRows after merge:")
print(len(current_day_test))

Current day shape:
(114017, 196)

Expected current-day rows:
114017

Rows after merge:
114017

In [121]:
# Validate previous-day interval columns

lag96_columns = [
    f"lag96_{column}"
    for column in traffic_columns
]

missing_lag96_columns = [
    column
    for column in lag96_columns
    if column not in current_day_test.columns
]

print(
    "Missing lag-96 interval columns:",
    missing_lag96_columns
)

print(
    "\nNumber of lag-96 interval columns:",
    len(lag96_columns)
)

Missing lag-96 interval columns: []

Number of lag-96 interval columns: 96

In [122]:
# Manually verify one previous-day interval

example = current_day_test.iloc[0]

site = example["NB_SCATS_SITE"]
detector = example["NB_DETECTOR"]

current_value = example["V00"]

previous_value = first_day[
    (
        first_day["NB_SCATS_SITE"] == site
    )
    &
    (
        first_day["NB_DETECTOR"] == detector
    )
]["V00"]

print("Site:", site)
print("Detector:", detector)

print("\nCurrent V00:", current_value)

print(
    "Previous-day V00:",
    previous_value.iloc[0]
)

print(
    "Stored lag96_V00:",
    example["lag96_V00"]
)

print(
    "\nMatch:",
    current_value == current_value
    and
    previous_value.iloc[0]
    == example["lag96_V00"]
)

Site: 100
Detector: 1

Current V00: 0
Previous-day V00: 2
Stored lag96_V00: 2.0

Match: True

In [123]:
# Convert current-day intervals into long format
# while carrying the matching previous-day interval as lag_96

def reshape_with_lag_96(data):
    """
    Convert current-day wide traffic data to long format
    and attach the previous-day same-interval traffic as lag_96.
    """

    current_rows = []

    for interval in traffic_columns:

        temp = data[
            [
                "NB_SCATS_SITE",
                "NB_DETECTOR",
                interval,
                f"lag96_{interval}"
            ]
        ].copy()

        temp["interval"] = interval

        temp = temp.rename(
            columns={
                interval: "volume",
                f"lag96_{interval}": "lag_96"
            }
        )

        current_rows.append(
            temp
        )

    result = pd.concat(
        current_rows,
        ignore_index=True
    )

    return result

In [124]:
# Test current-day + lag_96 reshaping

long_lag96_test = reshape_with_lag_96(
    current_day_test
)

print("Long-format shape:")
print(long_lag96_test.shape)

print("\nExpected rows:")
print(
    len(second_day) * len(traffic_columns)
)

display(
    long_lag96_test.head(10)
)

Long-format shape:
(10945632, 5)

Expected rows:
10945632

   NB_SCATS_SITE  NB_DETECTOR  volume  lag_96 interval
0            100            1       0     2.0      V00
1            100            2      11    12.0      V00
2            100            3      17    22.0      V00
3            100            4      14    17.0      V00
4            100            5       3     3.0      V00
5            100            6       0     0.0      V00
6            100            7       0     0.0      V00
7            100            8       0     0.0      V00
8            100            9       0     0.0      V00
9            100           10       0     0.0      V00

In [125]:
# Validate lag_96 after long-format conversion

test_row = long_lag96_test[
    long_lag96_test["interval"] == "V00"
].iloc[0]

site = test_row["NB_SCATS_SITE"]
detector = test_row["NB_DETECTOR"]

expected_lag96 = first_day[
    (
        first_day["NB_SCATS_SITE"] == site
    )
    &
    (
        first_day["NB_DETECTOR"] == detector
    )
]["V00"].iloc[0]

actual_lag96 = test_row["lag_96"]

print("Site:", site)
print("Detector:", detector)
print("Interval:", test_row["interval"])

print("\nExpected lag_96:", expected_lag96)
print("Actual lag_96:", actual_lag96)

print(
    "\nMatch:",
    expected_lag96 == actual_lag96
)

Site: 100
Detector: 1
Interval: V00

Expected lag_96: 2
Actual lag_96: 2.0

Match: True

In [126]:
# Validate lag_96 across all 96 intervals for one detector

example_site = site
example_detector = detector

validation_rows = long_lag96_test[
    (
        long_lag96_test["NB_SCATS_SITE"]
        == example_site
    )
    &
    (
        long_lag96_test["NB_DETECTOR"]
        == example_detector
    )
].copy()

print(
    "Intervals found:",
    len(validation_rows)
)

print(
    "Expected intervals:",
    len(traffic_columns)
)

print(
    "\nMissing lag_96 values:",
    validation_rows["lag_96"].isna().sum()
)

Intervals found: 96
Expected intervals: 96

Missing lag_96 values: 0

In [127]:
# Process one manageable batch with lag_96

def process_feature_batch(
    current_batch,
    previous_day
):
    """
    Process one small batch of site-detector records.

    The batch is reshaped into long format and receives:
    - calendar features
    - lag_1 to lag_4
    - rolling features
    - lag_96
    - next 15-minute target within the batch
    """

    # Add previous-day interval values
    batch_with_lag96 = add_lag_96_to_day(
        current_batch,
        previous_day
    )

    # Convert current intervals to long format
    data = reshape_with_lag_96(
        batch_with_lag96
    )

    # Convert interval names into time information
    data["interval_index"] = (
        data["interval"]
        .str.replace("V", "", regex=False)
        .astype("int8")
    )

    data["timestamp"] = (
        pd.to_datetime(
            current_batch["QT_INTERVAL_COUNT"]
            .iloc[0]
        )
        .normalize()
        +
        pd.to_timedelta(
            data["interval_index"] * 15,
            unit="m"
        )
    )

    # Calendar features
    data = add_time_features(
        data
    )

    # Short-term lags
    data = add_short_term_lags(
        data
    )

    # Rolling features
    data = add_rolling_features(
        data
    )

    # Target
    data = add_target(
        data
    )

    return data

In [128]:
# Test the batch-level processor

test_batch = first_day.iloc[
    :FEATURE_BATCH_SIZE
].copy()

batch_feature_test = process_feature_batch(
    test_batch,
    first_day
)

print("Batch feature shape:")
print(
    batch_feature_test.shape
)

print("\nMemory usage:")

batch_memory = (
    batch_feature_test
    .memory_usage(deep=True)
    .sum()
    / (1024 ** 2)
)

print(
    f"{batch_memory:.2f} MB"
)

display(
    batch_feature_test.head()
)

Batch feature shape:
(480000, 20)

Memory usage:
63.23 MB

,NB_SCATS_SITE,NB_DETECTOR,volume,lag_96,interval,interval_index,timestamp,hour,minute,day_of_week,is_weekend,time_index,lag_1,lag_2,lag_3,lag_4,rolling_mean_4,rolling_std_4,rolling_mean_8,target
470000,100,1,3,3,V94,94,2025-03-31 21:54:00,21,54,0,0,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
385000,100,1,7,7,V77,77,2025-03-31 21:55:00,21,55,0,0,87,3.0,NaN,NaN,NaN,NaN,NaN,NaN,15.0
300000,100,1,15,15,V60,60,2025-03-31 21:56:00,21,56,0,0,87,7.0,3.0,NaN,NaN,NaN,NaN,NaN,16.0
215000,100,1,16,16,V43,43,2025-03-31 21:57:00,21,57,0,0,87,15.0,7.0,3.0,NaN,NaN,NaN,NaN,16.0
130000,100,1,16,16,V26,26,2025-03-31 21:58:00,21,58,0,0,87,16.0,15.0,7.0,3.0,10.25,6.291529,NaN,1.0

In [129]:
# Validate batch feature columns

expected_batch_features = [
    "NB_SCATS_SITE",
    "NB_DETECTOR",
    "timestamp",
    "volume",
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_4",
    "lag_96",
    "rolling_mean_4",
    "rolling_std_4",
    "rolling_mean_8",
    "hour",
    "minute",
    "day_of_week",
    "is_weekend",
    "time_index",
    "target"
]

missing_batch_features = [
    column
    for column in expected_batch_features
    if column not in batch_feature_test.columns
]

print(
    "Missing batch features:",
    missing_batch_features
)

print(
    "\nBatch feature validation:",
    len(missing_batch_features) == 0
)

Missing batch features: []

Batch feature validation: True

In [130]:
# Test batch processor using two consecutive days

test_batch = second_day.iloc[
    :FEATURE_BATCH_SIZE
].copy()

batch_feature_test = process_feature_batch(
    test_batch,
    first_day
)

print("Batch feature shape:")
print(
    batch_feature_test.shape
)

print("\nMemory usage:")

batch_memory = (
    batch_feature_test
    .memory_usage(deep=True)
    .sum()
    / (1024 ** 2)
)

print(
    f"{batch_memory:.2f} MB"
)

Batch feature shape:
(480000, 20)

Memory usage:
63.23 MB

In [131]:
# Validate lag_96 inside the batch processor

example_site = batch_feature_test[
    "NB_SCATS_SITE"
].iloc[0]

example_detector = batch_feature_test[
    "NB_DETECTOR"
].iloc[0]

example_interval = "V00"

actual_value = batch_feature_test[
    (
        batch_feature_test["NB_SCATS_SITE"]
        == example_site
    )
    &
    (
        batch_feature_test["NB_DETECTOR"]
        == example_detector
    )
    &
    (
        batch_feature_test["time_index"]
        == 0
    )
]["lag_96"].iloc[0]

expected_value = first_day[
    (
        first_day["NB_SCATS_SITE"]
        == example_site
    )
    &
    (
        first_day["NB_DETECTOR"]
        == example_detector
    )
][example_interval].iloc[0]

print("Site:", example_site)
print("Detector:", example_detector)
print("Interval:", example_interval)

print("\nExpected lag_96:", expected_value)
print("Actual lag_96:", actual_value)

print(
    "\nMatch:",
    np.isclose(
        expected_value,
        actual_value,
        equal_nan=True
    )
)

Site: 100
Detector: 1
Interval: V00

Expected lag_96: 2
Actual lag_96: 2.0

Match: True

In [132]:
# Validate short-term lags in the batch processor

validation = batch_feature_test[
    [
        "NB_SCATS_SITE",
        "NB_DETECTOR",
        "timestamp",
        "volume",
        "lag_1",
        "lag_2",
        "lag_3",
        "lag_4"
    ]
].copy()

for lag in [1, 2, 3, 4]:

    expected = (
        validation
        .groupby(
            [
                "NB_SCATS_SITE",
                "NB_DETECTOR"
            ]
        )["volume"]
        .shift(lag)
    )

    mismatch = (
        ~np.isclose(
            validation[f"lag_{lag}"],
            expected,
            equal_nan=True
        )
    ).sum()

    print(
        f"lag_{lag} mismatches:",
        mismatch
    )

lag_1 mismatches: 0
lag_2 mismatches: 0
lag_3 mismatches: 0
lag_4 mismatches: 0

In [133]:
# Get the third complete day

third_day = next(day_iterator)

print("Third complete day shape:")
print(third_day.shape)

print("\nThird day start:")
print(
    third_day["QT_INTERVAL_COUNT"].min()
)

print("\nThird day end:")
print(
    third_day["QT_INTERVAL_COUNT"].max()
)

print(
    "\nUnique dates:",
    third_day["QT_INTERVAL_COUNT"]
    .dt.normalize()
    .nunique()
)

Third complete day shape:
(114057, 100)

Third day start:
2025-04-03 00:00:00

Third day end:
2025-04-03 00:00:00

Unique dates: 1

In [134]:
# Select the final 15-minute interval of the current day

current_day_final = second_day[
    [
        "NB_SCATS_SITE",
        "NB_DETECTOR",
        "V95"
    ]
].copy()

current_day_final = current_day_final.rename(
    columns={
        "V95": "current_volume"
    }
)

print(
    "Current-day final interval rows:",
    len(current_day_final)
)

display(
    current_day_final.head()
)

Current-day final interval rows: 114017

   NB_SCATS_SITE  NB_DETECTOR  current_volume
0            100            1               9
1            100            2              28
2            100            3              37
3            100            4              18
4            100            5               2

In [135]:
# Get the next day's first 15-minute interval

next_day_first = third_day[
    [
        "NB_SCATS_SITE",
        "NB_DETECTOR",
        "V00"
    ]
].copy()

next_day_first = next_day_first.rename(
    columns={
        "V00": "expected_target"
    }
)

print(
    "Next-day first interval rows:",
    len(next_day_first)
)

display(
    next_day_first.head()
)

Next-day first interval rows: 114057

   NB_SCATS_SITE  NB_DETECTOR  expected_target
0            100            1                5
1            100            2               10
2            100            3               24
3            100            4               15
4            100            5                1

In [136]:
# Validate the V95 -> next-day V00 target mapping

target_boundary_test = current_day_final.merge(
    next_day_first,
    on=[
        "NB_SCATS_SITE",
        "NB_DETECTOR"
    ],
    how="left",
    validate="one_to_one"
)

print(
    "Rows after merge:",
    len(target_boundary_test)
)

print(
    "Missing next-day targets:",
    target_boundary_test[
        "expected_target"
    ].isna().sum()
)

display(
    target_boundary_test.head(10)
)

Rows after merge: 114017
Missing next-day targets: 0

   NB_SCATS_SITE  NB_DETECTOR  current_volume  expected_target
0            100            1               9                5
1            100            2              28               10
2            100            3              37               24
3            100            4              18               15
4            100            5               2                1
5            100            6               0                0
6            100            7               0                0
7            100            8               0                0
8            100            9               0                0
9            100           10               0                0

In [137]:
# Manually verify one V95 -> next-day V00 target

example = target_boundary_test.iloc[0]

site = example["NB_SCATS_SITE"]
detector = example["NB_DETECTOR"]

expected = third_day[
    (
        third_day["NB_SCATS_SITE"] == site
    )
    &
    (
        third_day["NB_DETECTOR"] == detector
    )
]["V00"].iloc[0]

actual = example["expected_target"]

print("Site:", site)
print("Detector:", detector)

print(
    "\nSecond-day V95:",
    example["current_volume"]
)

print(
    "Expected target (third-day V00):",
    expected
)

print(
    "Stored target:",
    actual
)

print(
    "\nMatch:",
    np.isclose(
        expected,
        actual,
        equal_nan=True
    )
)

Site: 100
Detector: 1

Second-day V95: 9
Expected target (third-day V00): 5
Stored target: 5

Match: True

In [138]:
# Final columns to write to the feature dataset

PRODUCTION_FINAL_COLUMNS = [
    "NB_SCATS_SITE",
    "NB_DETECTOR",
    "timestamp",
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_4",
    "lag_96",
    "rolling_mean_4",
    "rolling_std_4",
    "rolling_mean_8",
    "hour",
    "minute",
    "day_of_week",
    "is_weekend",
    "time_index",
    "target"
]

print(
    "Number of final columns:",
    len(PRODUCTION_FINAL_COLUMNS)
)

print(
    "\nFinal columns:"
)

for column in PRODUCTION_FINAL_COLUMNS:
    print("-", column)

Number of final columns: 17

Final columns:
- NB_SCATS_SITE
- NB_DETECTOR
- timestamp
- lag_1
- lag_2
- lag_3
- lag_4
- lag_96
- rolling_mean_4
- rolling_std_4
- rolling_mean_8
- hour
- minute
- day_of_week
- is_weekend
- time_index
- target

In [139]:
# Prepare next-day V00 for the current day's final target

def prepare_next_day_target(next_day):
    """
    Prepare next-day V00 values used as the target
    for the previous day's V95.
    """

    target_data = next_day[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "V00"
        ]
    ].copy()

    target_data = target_data.rename(
        columns={
            "V00": "next_day_v00"
        }
    )

    return target_data

In [140]:
# Create the next-day target lookup

next_day_target = prepare_next_day_target(
    third_day
)

print(
    "Next-day target rows:",
    len(next_day_target)
)

print(
    "Missing next-day V00:",
    next_day_target["next_day_v00"].isna().sum()
)

display(
    next_day_target.head()
)

Next-day target rows: 114057
Missing next-day V00: 0

   NB_SCATS_SITE  NB_DETECTOR  next_day_v00
0            100            1             5
1            100            2            10
2            100            3            24
3            100            4            15
4            100            5             1

In [141]:
# Apply the next-day target to V95 observations

def apply_next_day_target(
    batch_features,
    next_day_target
):
    """
    Replace the target for 23:45 observations with
    the next day's 00:00 volume.
    """

    data = batch_features.copy()

    data = data.merge(
        next_day_target,
        on=[
            "NB_SCATS_SITE",
            "NB_DETECTOR"
        ],
        how="left",
        validate="many_to_one"
    )

    # V95 corresponds to time_index 95
    final_interval = (
        data["time_index"] == 95
    )

    data.loc[
        final_interval,
        "target"
    ] = data.loc[
        final_interval,
        "next_day_v00"
    ]

    data = data.drop(
        columns=["next_day_v00"]
    )

    return data

In [142]:
# Test the next-day target replacement

batch_with_final_target = apply_next_day_target(
    batch_feature_test,
    next_day_target
)

boundary_rows = batch_with_final_target[
    batch_with_final_target["time_index"] == 95
]

print(
    "V95 rows:",
    len(boundary_rows)
)

print(
    "Missing V95 targets:",
    boundary_rows["target"].isna().sum()
)

display(
    boundary_rows[
        [
            "NB_SCATS_SITE",
            "NB_DETECTOR",
            "timestamp",
            "volume",
            "target"
        ]
    ].head(10)
)

V95 rows: 25000
Missing V95 targets: 0

     NB_SCATS_SITE  NB_DETECTOR           timestamp  volume  target
42             100            1 2025-04-01 23:55:00      12     5.0
43             100            1 2025-04-01 23:56:00      12     5.0
44             100            1 2025-04-01 23:57:00      16     5.0
45             100            1 2025-04-01 23:58:00      14     5.0
46             100            1 2025-04-01 23:59:00       0     5.0
138            100            2 2025-04-01 23:55:00      62    10.0
139            100            2 2025-04-01 23:56:00     192    10.0
140            100            2 2025-04-01 23:57:00     131    10.0
141            100            2 2025-04-01 23:58:00     173    10.0
142            100            2 2025-04-01 23:59:00       2    10.0

In [143]:
# Manually verify one final-interval target

example = boundary_rows.iloc[0]

site = example["NB_SCATS_SITE"]
detector = example["NB_DETECTOR"]

expected_target = third_day[
    (
        third_day["NB_SCATS_SITE"] == site
    )
    &
    (
        third_day["NB_DETECTOR"] == detector
    )
]["V00"].iloc[0]

actual_target = example["target"]

print("Site:", site)
print("Detector:", detector)

print(
    "\nExpected target:",
    expected_target
)

print(
    "Actual target:",
    actual_target
)

print(
    "\nMatch:",
    np.isclose(
        expected_target,
        actual_target,
        equal_nan=True
    )
)

Site: 100
Detector: 1

Expected target: 5
Actual target: 5.0

Match: True

In [144]:
# Finalize one engineered batch

def finalize_feature_batch(
    current_batch,
    previous_day,
    next_day_target
):
    """
    Create the final modeling dataset for one raw batch.

    Steps:
    1. Add lag_96 from previous day
    2. Reshape current-day intervals
    3. Add calendar features
    4. Add short-term lags
    5. Add rolling features
    6. Add target
    7. Replace V95 target using next-day V00
    8. Keep only final modeling columns
    """

    # -----------------------------------------
    # Step 1: Add previous-day lag_96
    # -----------------------------------------

    data = add_lag_96_to_day(
        current_batch,
        previous_day
    )

    # -----------------------------------------
    # Step 2: Reshape
    # -----------------------------------------

    data = reshape_with_lag_96(
        data
    )

    # -----------------------------------------
    # Step 3: Add interval index
    # -----------------------------------------

    data["interval_index"] = (
        data["interval"]
        .str.replace("V", "", regex=False)
        .astype("int8")
    )

    # -----------------------------------------
    # Step 4: Create timestamp
    # -----------------------------------------

    current_date = pd.to_datetime(
        current_batch["QT_INTERVAL_COUNT"].iloc[0]
    ).normalize()

    data["timestamp"] = (
        current_date
        +
        pd.to_timedelta(
            data["interval_index"] * 15,
            unit="m"
        )
    )

    # -----------------------------------------
    # Step 5: Calendar features
    # -----------------------------------------

    data = add_time_features(
        data
    )

    # -----------------------------------------
    # Step 6: Short-term lags
    # -----------------------------------------

    data = add_short_term_lags(
        data
    )

    # -----------------------------------------
    # Step 7: Rolling features
    # -----------------------------------------

    data = add_rolling_features(
        data
    )

    # -----------------------------------------
    # Step 8: Normal target
    # -----------------------------------------

    data = add_target(
        data
    )

    # -----------------------------------------
    # Step 9: V95 → next-day V00
    # -----------------------------------------

    data = apply_next_day_target(
        data,
        next_day_target
    )

    # -----------------------------------------
    # Step 10: Keep final columns
    # -----------------------------------------

    data = data[
        PRODUCTION_FINAL_COLUMNS
    ]

    return data

In [145]:
# Test the complete finalized feature batch

final_batch_test = finalize_feature_batch(
    second_day.iloc[:FEATURE_BATCH_SIZE].copy(),
    first_day,
    next_day_target
)

print("Final batch shape:")
print(
    final_batch_test.shape
)

print("\nMemory usage:")

memory_mb = (
    final_batch_test
    .memory_usage(deep=True)
    .sum()
    / (1024 ** 2)
)

print(
    f"{memory_mb:.2f} MB"
)

print("\nColumns:")
print(
    final_batch_test.columns.tolist()
)

Final batch shape:
(480000, 17)

Memory usage:
50.35 MB

Columns:
['NB_SCATS_SITE', 'NB_DETECTOR', 'timestamp', 'lag_1', 'lag_2', 'lag_3', 'lag_4', 'lag_96', 'rolling_mean_4', 'rolling_std_4', 'rolling_mean_8', 'hour', 'minute', 'day_of_week', 'is_weekend', 'time_index', 'target']

In [146]:
# Validate final production schema

missing_final_columns = [
    column
    for column in PRODUCTION_FINAL_COLUMNS
    if column not in final_batch_test.columns
]

extra_columns = [
    column
    for column in final_batch_test.columns
    if column not in PRODUCTION_FINAL_COLUMNS
]

print(
    "Missing final columns:",
    missing_final_columns
)

print(
    "Extra columns:",
    extra_columns
)

print(
    "\nSchema validation:",
    (
        len(missing_final_columns) == 0
        and
        len(extra_columns) == 0
    )
)

Missing final columns: []
Extra columns: []

Schema validation: True

In [147]:
# Check missing values in the final modeling batch

missing_summary = (
    final_batch_test
    .isna()
    .sum()
    .sort_values(
        ascending=False
    )
)

display(
    missing_summary[
        missing_summary > 0
    ]
)

rolling_mean_8    40000
rolling_std_4     20000
rolling_mean_4    20000
lag_4             20000
lag_3             15000
lag_2             10000
lag_1              5000
target             5000
lag_96             1536
dtype: int64

In [148]:
# Determine how many rows are currently usable

complete_final_rows = (
    final_batch_test
    .notna()
    .all(axis=1)
)

print(
    "Total final rows:",
    len(final_batch_test)
)

print(
    "Complete rows:",
    complete_final_rows.sum()
)

print(
    "Rows containing NaN:",
    (~complete_final_rows).sum()
)

print(
    "\nUsable percentage:",
    f"{complete_final_rows.mean() * 100:.2f}%"
)

Total final rows: 480000
Complete rows: 433608
Rows containing NaN: 46392

Usable percentage: 90.33%

In [149]:
# Inspect the final engineered dataset

display(
    final_batch_test.head(20)
)

,NB_SCATS_SITE,NB_DETECTOR,timestamp,lag_1,lag_2,lag_3,lag_4,lag_96,rolling_mean_4,rolling_std_4,rolling_mean_8,hour,minute,day_of_week,is_weekend,time_index,target
0,100,1,2025-04-01 21:54:00,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,21,54,1,0,87,14.0
1,100,1,2025-04-01 21:55:00,6.0,NaN,NaN,NaN,7.0,NaN,NaN,NaN,21,55,1,0,87,9.0
2,100,1,2025-04-01 21:56:00,14.0,6.0,NaN,NaN,15.0,NaN,NaN,NaN,21,56,1,0,87,13.0
3,100,1,2025-04-01 21:57:00,9.0,14.0,6.0,NaN,16.0,NaN,NaN,NaN,21,57,1,0,87,15.0
4,100,1,2025-04-01 21:58:00,13.0,9.0,14.0,6.0,16.0,10.50,3.696846,NaN,21,58,1,0,87,1.0
5,100,1,2025-04-01 21:59:00,15.0,13.0,9.0,14.0,1.0,12.75,2.629956,NaN,21,59,1,0,87,9.0
6,100,1,2025-04-01 22:09:00,1.0,15.0,13.0,9.0,3.0,9.50,6.191392,NaN,22,9,1,0,88,14.0
7,100,1,2025-04-01 22:10:00,9.0,1.0,15.0,13.0,13.0,9.50,6.191392,NaN,22,10,1,0,88,15.0
8,100,1,2025-04-01 22:11:00,14.0,9.0,1.0,15.0,13.0,9.75,6.396614,10.125,22,11,1,0,88,12.0
9,100,1,2025-04-01 22:12:00,15.0,14.0,9.0,1.0,14.0,9.75,6.396614,11.250,22,12,1,0,88,9.0
10,100,1,2025-04-01 22:13:00,12.0,15.0,14.0,9.0,11.0,12.50,2.645751,11.000,22,13,1,0,88,1.0
11,100,1,2025-04-01 22:14:00,9.0,12.0,15.0,14.0,1.0,12.50,2.645751,11.000,22,14,1,0,88,10.0
12,100,1,2025-04-01 22:25:00,1.0,9.0,12.0,15.0,8.0,9.25,6.020797,9.500,22,25,1,0,89,21.0
13,100,1,2025-04-01 22:26:00,10.0,1.0,9.0,12.0,14.0,8.00,4.830459,8.875,22,26,1,0,89,11.0
14,100,1,2025-04-01 22:27:00,21.0,10.0,1.0,9.0,14.0,10.25,8.220908,11.375,22,27,1,0,89,4.0
15,100,1,2025-04-01 22:28:00,11.0,21.0,10.0,1.0,5.0,10.75,8.180261,11.625,22,28,1,0,89,0.0
16,100,1,2025-04-01 22:29:00,4.0,11.0,21.0,10.0,0.0,11.50,7.047458,10.375,22,29,1,0,89,16.0
17,100,1,2025-04-01 22:40:00,0.0,4.0,11.0,21.0,12.0,9.00,9.201449,8.500,22,40,1,0,90,22.0
18,100,1,2025-04-01 22:41:00,16.0,0.0,4.0,11.0,18.0,7.75,7.135592,9.000,22,41,1,0,90,14.0
19,100,1,2025-04-01 22:42:00,22.0,16.0,0.0,4.0,11.0,10.50,10.246951,10.625,22,42,1,0,90,10.0

In [150]:
print(
    final_batch_test.dtypes
)

NB_SCATS_SITE              int64
NB_DETECTOR                int64
timestamp         datetime64[us]
lag_1                    float64
lag_2                    float64
lag_3                    float64
lag_4                    float64
lag_96                   float64
rolling_mean_4           float64
rolling_std_4            float64
rolling_mean_8           float64
hour                       int32
minute                     int32
day_of_week                int32
is_weekend                  int8
time_index                  int8
target                   float64
dtype: object

In [151]:
# Clean one finalized feature batch

def clean_final_batch(data):
    """
    Keep only rows where every modeling feature and target
    is available.
    """

    before_rows = len(data)

    data = data.dropna(
        subset=PRODUCTION_FINAL_COLUMNS
    ).copy()

    after_rows = len(data)

    print(
        f"Rows before cleaning: {before_rows:,}"
    )

    print(
        f"Rows after cleaning:  {after_rows:,}"
    )

    print(
        f"Rows removed:         {before_rows - after_rows:,}"
    )

    return data

In [152]:
# Test final batch cleaning

clean_batch_test = clean_final_batch(
    final_batch_test
)

print(
    "\nClean batch shape:"
)

print(
    clean_batch_test.shape
)

print(
    "\nRemaining missing values:"
)

print(
    clean_batch_test
    .isna()
    .sum()
    .sum()
)

Rows before cleaning: 480,000
Rows after cleaning:  433,608
Rows removed:         46,392

Clean batch shape:
(433608, 17)

Remaining missing values:
0

In [153]:
# Final validation after removing incomplete rows

assert (
    clean_batch_test
    .isna()
    .sum()
    .sum()
    == 0
)

assert (
    clean_batch_test.columns.tolist()
    == PRODUCTION_FINAL_COLUMNS
)

print("Final cleaned batch validation: PASSED")
print(
    "Rows:",
    len(clean_batch_test)
)

print(
    "Columns:",
    len(clean_batch_test.columns)
)

Final cleaned batch validation: PASSED
Rows: 433608
Columns: 17

In [154]:
# Test Parquet output

TEST_PARQUET_PATH = (
    FEATURED_DATA_DIR
    / "test_batch.parquet"
)

clean_batch_test.to_parquet(
    TEST_PARQUET_PATH,
    index=False
)

print(
    "Parquet written successfully:"
)

print(TEST_PARQUET_PATH)

print(
    "\nFile size:"
)

file_size_mb = (
    TEST_PARQUET_PATH.stat().st_size
    / (1024 ** 2)
)

print(
    f"{file_size_mb:.2f} MB"
)

Parquet written successfully:
c:\Users\Aditya\Smart_traffic_management\data\processed\featured\test_batch.parquet

File size:
3.00 MB

In [161]:
# Read the test Parquet file

parquet_test = pd.read_parquet(
    TEST_PARQUET_PATH
)

print(
    "Read-back shape:"
)

print(
    parquet_test.shape
)

print(
    "\nColumns:"
)

print(
    parquet_test.columns.tolist()
)

print(
    "\nMissing values:"
)

print(
    parquet_test.isna().sum().sum()
)

Read-back shape:
(433608, 17)

Columns:
['NB_SCATS_SITE', 'NB_DETECTOR', 'timestamp', 'lag_1', 'lag_2', 'lag_3', 'lag_4', 'lag_96', 'rolling_mean_4', 'rolling_std_4', 'rolling_mean_8', 'hour', 'minute', 'day_of_week', 'is_weekend', 'time_index', 'target']

Missing values:
0

In [162]:
# Remove temporary Parquet test file

if TEST_PARQUET_PATH.exists():

    TEST_PARQUET_PATH.unlink()

print(
    "Temporary Parquet test file removed."
)

Temporary Parquet test file removed.

In [163]:
# Write one cleaned feature batch to Parquet

def write_feature_batch(
    data,
    output_dir,
    part_number
):
    """
    Write one cleaned feature batch to a Parquet file.
    """

    output_path = (
        output_dir
        / f"part_{part_number:06d}.parquet"
    )

    data.to_parquet(
        output_path,
        engine="pyarrow",
        index=False
    )

    return output_path

In [164]:
# Test the production Parquet writer

TEST_PART_NUMBER = 999999

test_output_path = write_feature_batch(
    clean_batch_test,
    FEATURED_DATA_DIR,
    TEST_PART_NUMBER
)

print(
    "Test Parquet path:"
)

print(test_output_path)

print(
    "\nFile exists:",
    test_output_path.exists()
)

print(
    "File size:",
    f"{test_output_path.stat().st_size / (1024**2):.2f} MB"
)

Test Parquet path:
c:\Users\Aditya\Smart_traffic_management\data\processed\featured\part_999999.parquet

File exists: True
File size: 3.00 MB

In [165]:
# Verify the production writer output

production_test_read = pd.read_parquet(
    test_output_path,
    engine="pyarrow"
)

print(
    "Shape:",
    production_test_read.shape
)

print(
    "Columns:",
    len(production_test_read.columns)
)

print(
    "Missing values:",
    production_test_read.isna().sum().sum()
)

print(
    "\nProduction writer validation:",
    (
        production_test_read.shape
        == clean_batch_test.shape
        and
        production_test_read.columns.tolist()
        == clean_batch_test.columns.tolist()
        and
        production_test_read.isna().sum().sum()
        == 0
    )
)

Shape: (433608, 17)
Columns: 17
Missing values: 0

Production writer validation: True

In [166]:
# Remove the temporary production writer test

if test_output_path.exists():
    test_output_path.unlink()

print(
    "Temporary writer test removed."
)

Temporary writer test removed.

In [167]:
# Prepare the three-day production simulation

simulation_previous_day = first_day
simulation_current_day = second_day
simulation_next_day = third_day

simulation_next_target = prepare_next_day_target(
    simulation_next_day
)

print("Previous day:")
print(
    simulation_previous_day[
        "QT_INTERVAL_COUNT"
    ].dt.date.unique()
)

print("\nCurrent day:")
print(
    simulation_current_day[
        "QT_INTERVAL_COUNT"
    ].dt.date.unique()
)

print("\nNext day:")
print(
    simulation_next_day[
        "QT_INTERVAL_COUNT"
    ].dt.date.unique()
)

Previous day:
[datetime.date(2025, 4, 1)]

Current day:
[datetime.date(2025, 4, 2)]

Next day:
[datetime.date(2025, 4, 3)]

In [168]:
# Process one complete day in production-style batches

simulation_output_dir = (
    FEATURED_DATA_DIR
    / "simulation"
)

simulation_output_dir.mkdir(
    parents=True,
    exist_ok=True
)

simulation_part_number = 0

simulation_total_rows = 0

for batch_number, raw_batch in enumerate(
    iter_day_batches(
        simulation_current_day
    ),
    start=1
):

    # -----------------------------------------
    # Feature engineering
    # -----------------------------------------

    feature_batch = finalize_feature_batch(
        raw_batch,
        simulation_previous_day,
        simulation_next_target
    )

    # -----------------------------------------
    # Remove incomplete rows
    # -----------------------------------------

    clean_batch = clean_final_batch(
        feature_batch
    )

    # -----------------------------------------
    # Skip empty batches
    # -----------------------------------------

    if clean_batch.empty:
        continue

    # -----------------------------------------
    # Write to Parquet
    # -----------------------------------------

    simulation_part_number += 1

    output_path = write_feature_batch(
        clean_batch,
        simulation_output_dir,
        simulation_part_number
    )

    simulation_total_rows += len(
        clean_batch
    )

    print(
        f"Batch {batch_number}: "
        f"{len(clean_batch):,} rows → "
        f"{output_path.name}"
    )

print(
    "\nSimulation complete."
)

print(
    "Total rows written:",
    f"{simulation_total_rows:,}"
)

print(
    "Parquet parts:",
    simulation_part_number
)

Rows before cleaning: 480,000
Rows after cleaning:  433,608
Rows removed:         46,392
Batch 1: 433,608 rows → part_000001.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 2: 435,000 rows → part_000002.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 3: 435,000 rows → part_000003.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 4: 435,000 rows → part_000004.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 5: 435,000 rows → part_000005.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 6: 435,000 rows → part_000006.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 7: 435,000 rows → part_000007.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 8: 435,000 rows → part_000008.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 9: 435,000 rows → part_000009.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 10: 435,000 rows → part_000010.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 11: 435,000 rows → part_000011.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 12: 435,000 rows → part_000012.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 13: 435,000 rows → part_000013.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 14: 435,000 rows → part_000014.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 15: 435,000 rows → part_000015.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 16: 435,000 rows → part_000016.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 17: 435,000 rows → part_000017.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 18: 435,000 rows → part_000018.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 19: 435,000 rows → part_000019.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 20: 435,000 rows → part_000020.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 21: 435,000 rows → part_000021.parquet
Rows before cleaning: 480,000
Rows after cleaning:  435,000
Rows removed:         45,000
Batch 22: 435,000 rows → part_000022.parquet
Rows before cleaning: 385,632
Rows after cleaning:  349,479
Rows removed:         36,153
Batch 23: 349,479 rows → part_000023.parquet

Simulation complete.
Total rows written: 9,918,087
Parquet parts: 23

In [169]:
# Inspect simulation Parquet output

simulation_files = sorted(
    simulation_output_dir.glob(
        "part_*.parquet"
    )
)

print(
    "Parquet files created:",
    len(simulation_files)
)

total_disk_rows = 0

for file_path in simulation_files:

    df_check = pd.read_parquet(
        file_path,
        columns=["target"]
    )

    total_disk_rows += len(
        df_check
    )

    del df_check

print(
    "Rows stored on disk:",
    f"{total_disk_rows:,}"
)

Parquet files created: 23
Rows stored on disk: 9,918,087

In [170]:
# Validate one production partition

sample_partition = pd.read_parquet(
    simulation_files[0]
)

print(
    "Shape:",
    sample_partition.shape
)

print(
    "\nColumns:",
    sample_partition.columns.tolist()
)

print(
    "\nMissing values:",
    sample_partition.isna().sum().sum()
)

print(
    "\nDtypes:"
)

print(
    sample_partition.dtypes
)

Shape: (433608, 17)

Columns: ['NB_SCATS_SITE', 'NB_DETECTOR', 'timestamp', 'lag_1', 'lag_2', 'lag_3', 'lag_4', 'lag_96', 'rolling_mean_4', 'rolling_std_4', 'rolling_mean_8', 'hour', 'minute', 'day_of_week', 'is_weekend', 'time_index', 'target']

Missing values: 0

Dtypes:
NB_SCATS_SITE              int64
NB_DETECTOR                int64
timestamp         datetime64[us]
lag_1                    float64
lag_2                    float64
lag_3                    float64
lag_4                    float64
lag_96                   float64
rolling_mean_4           float64
rolling_std_4            float64
rolling_mean_8           float64
hour                       int32
minute                     int32
day_of_week                int32
is_weekend                  int8
time_index                  int8
target                   float64
dtype: object

In [171]:
# Remove the temporary simulation output

import shutil

if simulation_output_dir.exists():

    shutil.rmtree(
        simulation_output_dir
    )

print(
    "Simulation output removed."
)

print(
    "Simulation directory exists:",
    simulation_output_dir.exists()
)

Simulation output removed.
Simulation directory exists: False

In [172]:
# Clean the production feature directory

existing_feature_files = list(
    FEATURED_DATA_DIR.glob("part_*.parquet")
)

print(
    "Existing production files:",
    len(existing_feature_files)
)

for file_path in existing_feature_files:
    file_path.unlink()

print(
    "Production output directory cleaned."
)

print(
    "Remaining Parquet files:",
    len(
        list(
            FEATURED_DATA_DIR.glob(
                "part_*.parquet"
            )
        )
    )
)

Existing production files: 0
Production output directory cleaned.
Remaining Parquet files: 0

In [173]:
# Production pipeline configuration

PRODUCTION_CHUNKSIZE = 50_000

PRODUCTION_BATCH_SIZE = 5_000

PRODUCTION_OUTPUT_DIR = (
    FEATURED_DATA_DIR
)

print(
    "CSV chunk size:",
    PRODUCTION_CHUNKSIZE
)

print(
    "Feature batch size:",
    PRODUCTION_BATCH_SIZE
)

print(
    "Output directory:",
    PRODUCTION_OUTPUT_DIR
)

CSV chunk size: 50000
Feature batch size: 5000
Output directory: c:\Users\Aditya\Smart_traffic_management\data\processed\featured